defaultBaseImage: registry.access.redhat.com/ubi8/ubi
baseImageOverrides:
  github.com/openshift-pipelines/operator/cmd/operator: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/openshift-pipelines/operator/cmd/webhook: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/openshift-pipelines/operator/cmd/proxy-webhook: registry.access.redhat.com/ubi8/ubi-minimal
