versions:
  current: 5.0.5-481
  previous: 5.0.5-480
  previous_range: 1.14.0
  channel: pipelines-5.0
  openshift:
    latest: 4.17 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/controller@sha256:760f2d3c810066b4e1f36aedc9d43a1d1009600e696338370f913dd352db28b4
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/webhook@sha256:033281fbe974825884f31a68225ae16ee204f22ff9c7c8d48b40757c7f7e68c3
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/resolvers@sha256:5b0012ccc0d489240db83b62f4e7cf68e967adbb98883fd5654f35f889479312
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/events@sha256:70c54dd93d6f463fa1c2445b4153efb653ac92664c4519429080376dea6c3257
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/entrypoint@sha256:9fce6a3fe153e67460e5628e15c98725dbc4c9c32ce724f21ac43cb5a270dfc3
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/workingdirinit@sha256:3f86e9f15dbfd9c6abe519c2dd73de650806b120856345d398bf7d5520407f08
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/nop@sha256:6a37b1a248154250513a24113847c4f5c1816fb3153ad5b896df3a52c39ff157
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-next/entrypoint@sha256:9fce6a3fe153e67460e5628e15c98725dbc4c9c32ce724f21ac43cb5a270dfc3
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-next/controller@sha256:7ccf167d37cc0feebed06886f5737f1827118715fed657b1e48d2024866c2fd8
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-next/webhook@sha256:e61c169b5f8ebc564e887d1adcf1e14aff2c48f56bcb0e2e6777f659053ec0b8
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-next/core-interceptors@sha256:5ab6bf62553439a84dd38d0d96a509ee45c16b8f92ecdf8e6796fe768ec7c7f9
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-next/eventlistenersink@sha256:0ebba105c0c5a59c62a2bc15504fcc46e49bb10e30b752ab27ab5bd34a8f7c55
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-next/controller@sha256:b23edef1ff103cd07cfef15c7e560cd0cf8d41fb2abc3f4c03fad7af5e6b6127
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-next/db-migration@sha256:e69d5da6946ad62201ae985d54878b6aa96705b45190abc99577256267ce3487
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-next/hub-api@sha256:86a687b8e9182deb44281d990e63628528d0ecfa47b0b64952953b3711454bff
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-next/hub-ui@sha256:9ac62ef5dc97f189a47e41b4f219efd300f39be81f2c9175119caadafbce2fc9
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-next/watcher@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-next/api@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-next/retention-policy-agent@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-next/tkn@sha256:b9b12b731c66413f81646f822f546c2c355d95c4a43aef7a833e6419cdf98de0
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-next/tkn@sha256:b9b12b731c66413f81646f822f546c2c355d95c4a43aef7a833e6419cdf98de0
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-next/tkn@sha256:b9b12b731c66413f81646f822f546c2c355d95c4a43aef7a833e6419cdf98de0
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-next/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-next/webhook@sha256:de5c7f6351ca055649153d10c2e2102f8b2bbc05b682a2907ec84cb2b048369e
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-next/controller@sha256:3559e2719a54b641c43bc8ce42f13abd73813cdad926936d43f06a1df54d2365
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-next/controller@sha256:17cb8cb5cb772a879991a5e04f682d78b293be53e64bc0e1c086cfc2a3bb7d9a
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-next/watcher@sha256:6a8d8def35e5f9caf4d959fb5d590416c40acc1bdc26405378db9011290d60f7
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-next/webhook@sha256:f238aaa302a16c68f2eb2eccf84dea1c7c71cea09ead3aa717db793c72289503
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-next/operator@sha256:9e5a8c2a5557688c091e216c4028c211d73cd7f260bf3eb02793999f641264bc
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-next/operator@sha256:9e5a8c2a5557688c091e216c4028c211d73cd7f260bf3eb02793999f641264bc
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-next/proxy@sha256:f7a4528d33cc8302b685190cfa2c41cb7be9c1511c2a55edcf0dad10e6bda51b
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-next/webhook@sha256:f9ed812ef309c8844c70ef11a38fad526669fa2f32f877cd74306af8871bf642
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
  - name: IMAGE_ADDONS_KN
    value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
  - name: IMAGE_ADDONS_SKOPEO_RESULTS
    value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
  - name: IMAGE_ADDONS_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
  - name: IMAGE_ADDONS_LOAD_SCRIPTS
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GENERATE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_PREPARE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GOALS
    value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
