versions:
  current: 5.0.5-481
  previous: 1.18.0
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-controller-rhel8@sha256:66f1badb9c1f0f3092b87602a1345594f1b637dcf9500e596922c3eec7d3948f
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-webhook-rhel8@sha256:3e9cebc4b22865197a96e72cd442f3671eba2ec6e831433cc627377c1d408c37
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-resolvers-rhel8@sha256:72553f8cc9bf03682285c30b4b95df12fcacf0a1603bccd843319730d87231c4
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-events-rhel8@sha256:51b6d665fb4121ec04ffc0ea69b144b6b6ccdf983be50139b18e49871ac21b92
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:648a64e5d085a81567d8c927ea80b38f19dad921fbc44c26a17777685b4b6a41
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-workingdirinit-rhel8@sha256:d1b3ab1f101705620a6039c1b08f651fd3a742a700b2c6c0318cd05527424ef2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-nop-rhel8@sha256:9292fd9f06dacd5aa1248813b4b6c9e4f00abe6cb4ca1d8025f84ec0ff513532
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:648a64e5d085a81567d8c927ea80b38f19dad921fbc44c26a17777685b4b6a41
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-sidecarlogresults-rhel8@sha256:460aae7b02a4e71e89c369e4e86056b453493b72e63db602e09245de4a94d504
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-controller-rhel8@sha256:08a4a04b04345d56b7375e2a8bfdeb531c88ea72ec2baf9de58fe226ccfc1b5e
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-webhook-rhel8@sha256:fcab4493bb0f4ce482d85ce47f07a18ad0351d55153fe09520ae8153f0b2dfac
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-core-interceptors-rhel8@sha256:9790e1a4a42513f0e6e04b64f93baa57727e4baa719db7aed9e7f4a4840582b4
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-eventlistenersink-rhel8@sha256:cf4463d2369d37e7729830056030226c995696572a7e0b9c4f7825a1b9d0b89c
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/chains-controller-rhel8@sha256:0f4a3750ae7bb4986852de7bf4b0808817f78e94f9fea79c81b29aad2d5f1b27
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-db-migration-rhel8@sha256:8f9d4e51ea20705e2a2f1607c6313056a149074b183ca1eacde6056d9ca28d01
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-api-rhel8@sha256:b1e4518704cdbe5dda3149636dc65ee5739e93cae09391be0664582673537b9c
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-ui-rhel8@sha256:cdf80ed9b9a7daf2a35796001099cbfba396b28997d4be8aa62064aff970deec
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-watcher-rhel8@sha256:07da7ff3dda3242d69fdfb2393033633ec9bc20daab62666c5958abdb8c4eb67
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-api-rhel8@sha256:cc7b7716686285623467e28528290292c741b237dc0dbfe833a062d3c4a20b2a
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-retention-policy-agent-rhel8@sha256:65a3d8b016905f03e23a111e091eb3998179ff9c7f0c932b1bde2d22e9f694a0
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:61dc77ab93f67ad9af72cb2af7a93a3febc81a77b831618651d1c9b016cc201a
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:61dc77ab93f67ad9af72cb2af7a93a3febc81a77b831618651d1c9b016cc201a
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:61dc77ab93f67ad9af72cb2af7a93a3febc81a77b831618651d1c9b016cc201a
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-webhook-rhel8@sha256:32416df654c142f9f5ace228c25eb6f0edc9f1aa49dd55caf65d1a4102e722b4
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-controller-rhel8@sha256:0b53c52e0491d1c3d229c0140f174be3e2339cf6caaa043ba13f18806ce2d10a
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-controller-rhel8@sha256:9568d8106c4ddf67889d6e4c064198f557a1674c0dd1fc79e54ace2a11a28237
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-webhook-rhel8@sha256:d7150b8f90d643d91bd3efdb341e61f7350ebb6a806a816e4c79d6c2af5dc337
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-watcher-rhel8@sha256:e479e665886188e0cefe8f03fb78db3e3cae34cc1ebf9f3a8733eb813fea9ba8
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-cli-rhel8@sha256:b841a6038b545aa9f5c4389ea86ada79001c32299e62854732eff3d8c4e83b80
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:7cf6c618975f335cb8d7178e582e04c35832223410e276d68dc33fdb7327b169
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:7cf6c618975f335cb8d7178e582e04c35832223410e276d68dc33fdb7327b169
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-proxy-rhel8@sha256:690c5ca3b9a86ca7cf60d7727f42aea7b9e15c20afa02d5479914596063f5109
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-webhook-rhel8@sha256:e7c38625f8699310f077835efcd105deb36a97e0038e87fc5d169a38a579402a
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/console-plugin-rhel8@sha256:d7721f5c3c7ed4bc0a0961e2c4b5ec3416d62e5cfbd2704488e063b22c23a141
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-bundle-rhel8@sha256:f2162408b5b02c6b1c819c1ec18f1e2c4e8a97e9271545ae4f8ad6dd18b42efa
