versions:
  current: 1.19.3
  previous: 1.19.2
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.19 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:2c3074ecc0c74d508020bf1e11667d868150915b55d436a43c2b4fc22815bf48
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:b8cdf2a1873a3df1fb8b8f6d58d06235cef28d228abd70d0bb83cdcfbe3bc230
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:31a40f8095a3f8cd04750810d964572339965ae0b2d357c57c0b671a95e1cdbe
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:5f39f9e61ddbce92629e6502bbef737365c8a1bb2dc2ecaf9f9d8092dea844c9
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:974c3dac770dd47383fdbf333a71b43750c7f0b9eece353dfaea4d575368ded7
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:c3ba6b9652205407cc4d4d47b4a928fe8fa86ce4427e6b44ee1d53faf3455f21
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:1b3805a74178c5ed27dd3586183c5d70900df307cd14117901b890487deab466
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:974c3dac770dd47383fdbf333a71b43750c7f0b9eece353dfaea4d575368ded7
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:d42980d8a07b315f004f50b68c2dcde614a1dcb4f0ff1c29cc08edfa610d7e90
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:22095c436562ff92771d9349f57d007d82415dae519e3da1de7d51e3f1042a93
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:25bcdb30f0fe34300c4f61f62513f4853f65fe11bafde58bcf19b7b3c3fb9af7
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:92b8c92eb0bec102215b97f1d60d76c7a57747aeec9594ce1e0e46f7c27391d6
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:8bcaeaa751c61eb927d6353984f81d6a92b4bd4f9a5be9dc620a11b06ff9e6ba
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:90a5eb2c0decb72234cbea5354bb7737cebc53c467229b2c16a1425b4bf408dc
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:28258903330a0715141e4685b3760ff18b0d75da0694985bba7c3345d7808b5f
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:ba596c629fe8b5b70db97923ff11392dc12115c8e7afefee0d48c12440b8dd86
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:10c620aa3a9c4bfbca185fb460e2521473a5fe6d518342b89a3dada5cf14e65a
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:2d2499b7b12aace07c4b5ab4121caad445aab5bc8dd73377171683b36d417d73
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:3f7e1d83eb1e21860cc2ae0bfe3abe8c9058e92a69698dba9d5871069016e90d
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:3b1c6f8acdf17a5185413147e0248baa559378ed79e08cb098c724036020576e
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:198cf9e5c9641757a0453dec2747a24b018a9b85e10eb0dfdc7a2e75ed09cf6d
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:198cf9e5c9641757a0453dec2747a24b018a9b85e10eb0dfdc7a2e75ed09cf6d
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:198cf9e5c9641757a0453dec2747a24b018a9b85e10eb0dfdc7a2e75ed09cf6d
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:a90a6c269b3fc4c77652d4862878211eee5eca1d8047e561d07e3ef1292e52f5
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:251c87e2c48e7f377bcb399ed64d50dff11de3459629a73a63bac17c353eb16b
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:6aaabb9af37e46a856371e29f141de6b0fac623128099bb927fc30f8f61e9db4
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:37e2f1fb8a2b4c7ac3d5390ba68a9bf98a0c83a38567b6a9778764061b3d2bab
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:fd6f4cd7801d7c20cf5a6e546022136404212da5d9997750e643f6e640b00e3d
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:d000daec36a6cdbe41a85ee4eac24a712f7628441a412f751baf8d7778626f62
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:c9fbb018a70df9a542236ace556fa3343ae350f43c0629f13e525854508f73f9
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:c9fbb018a70df9a542236ace556fa3343ae350f43c0629f13e525854508f73f9
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:b247e9f3a2db32b575999387ef4f91d685a67c1f3950a6e265e1fe14c1fac196
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:13608cfe2b87535776c65728aa40cfaa84ccf63afe64d1f2e799ea0e26819239
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:22cfadc42e793553182acf05a34fb6a7ae0d7055431c2e393699ecfeb171b173
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:22cfadc42e793553182acf05a34fb6a7ae0d7055431c2e393699ecfeb171b173
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:80af5fa2d87e7c405f16575519293ca7fccc49d635b4f3d0d334dea4fbd28721
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:80af5fa2d87e7c405f16575519293ca7fccc49d635b4f3d0d334dea4fbd28721
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:80af5fa2d87e7c405f16575519293ca7fccc49d635b4f3d0d334dea4fbd28721
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:80af5fa2d87e7c405f16575519293ca7fccc49d635b4f3d0d334dea4fbd28721
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:80af5fa2d87e7c405f16575519293ca7fccc49d635b4f3d0d334dea4fbd28721
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:80af5fa2d87e7c405f16575519293ca7fccc49d635b4f3d0d334dea4fbd28721
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:7a0c6794e9284209dc131f3087ffc01fd5946e20a9261422808c6dd3938407de
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:095e93f8dd31a0985d6fef6a6168da456630febe89ab9e0cb9480170f1036541
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:11583e8717bb2b736c6c629498308047f6b2cf744543331abcca93079a2d601e
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:aa1b6f374643ed4e89ba194afde8a5138e401c8cdeb45a6bb5df5b608f58358b
