versions:
  current: 5.0.5-593
  previous: 5.0.5-592
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-controller-rhel9@sha256:de11358c3ca78a8551e63c6570bcc1ff503831c92eada17a2b32d163724fe1dd
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-webhook-rhel9@sha256:030de97cd153fe297c810f45701b216dd6a166720b405efb9fd295f41f2f97ae
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-resolvers-rhel9@sha256:f87f0140ad280e0433dbfc05b30ac32c03bf5ec9b013586541c258b17e5abee2
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-events-rhel9@sha256:983dbd7eac2da520e2324ffe9dffc3b1cca51812492f10c19d5a926e17d24451
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:ec78f4e395dd23d41837392faf73882ae9ec566042fec5b8c45afec275ba3055
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-workingdirinit-rhel9@sha256:d87786e3ad10d666250c733fbeba2cb6dac46047f936b1d8021b8b8c975b39a4
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-nop-rhel9@sha256:cb08b0a40112e715112a7bddbbb48fdc3eae2a408e5ebe42543bdee877b24096
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:ec78f4e395dd23d41837392faf73882ae9ec566042fec5b8c45afec275ba3055
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-sidecarlogresults-rhel9@sha256:24a60f29f5b91b8101786a625434186a5e4ba4e60db417a290d55be5cce221d4
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-controller-rhel9@sha256:3e6d4b50ce2cca9f22fc28e3427d5a6b865527495a082066bcd80d1a88da4095
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-webhook-rhel9@sha256:a7317f6ca00613e02608bcaf14d61a7ddcbf48cada5c5f977f4fc6154941b272
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-core-interceptors-rhel9@sha256:6833d261bd1b90efd3a60b9aaf63952bcb1cc0a3348f352dde0399809d197ac9
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-eventlistenersink-rhel9@sha256:2aa8a15c9b8b35fd1d32c4dae94995eabff0376341bdad9de5bd6f3ab5db9a35
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/chains-controller-rhel9@sha256:9ea78ebdd650d6a3845a21ad775d63d5e8b007613755161b3176689100ccd049
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-db-migration-rhel9@sha256:8f9d4e51ea20705e2a2f1607c6313056a149074b183ca1eacde6056d9ca28d01
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-api-rhel9@sha256:ff8a7ee35e643f48cce781f7a8f3d6d076b84c35067daf68bb6c5bf2ddcd5e90
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-ui-rhel9@sha256:29ebf1ee68f1b13ee1ff00ac022e4f4ee32ae75021df15adc0c26a19ca57c266
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-watcher-rhel9@sha256:e65e27b13d8e86892dc01206f8828fc8bfcd01228b2d15e28a10739ad69de2db
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-api-rhel9@sha256:f001fdaaca88f93a1a7bcd61b16f0f58c984592e18cd1758193305eb1c4dcf04
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-retention-policy-agent-rhel9@sha256:f627477cff2b590b299dd9eafe76af28891d954e22a87d5f2c6a844d30eab5b8
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:afad5f9f03664ffd5a2b303c6168ff3a3c54cdad48cf890baca4adaf3bb8d301
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:afad5f9f03664ffd5a2b303c6168ff3a3c54cdad48cf890baca4adaf3bb8d301
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:afad5f9f03664ffd5a2b303c6168ff3a3c54cdad48cf890baca4adaf3bb8d301
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-webhook-rhel9@sha256:32416df654c142f9f5ace228c25eb6f0edc9f1aa49dd55caf65d1a4102e722b4
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-controller-rhel9@sha256:0b53c52e0491d1c3d229c0140f174be3e2339cf6caaa043ba13f18806ce2d10a
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-controller-rhel9@sha256:e41625f49eed20f7b3207e02c1c6de9028ebc8de1f951202e93fd6eb7adf7949
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-webhook-rhel9@sha256:44342dca036be7ad4dc451cda6c722518211d3df8c85fb66bdbbfc42d2341848
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-watcher-rhel9@sha256:ccc1c798edf8800ddd5b0e72abb518fa1b1a64bc1e8d209a412bfb65c7d16933
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-cli-rhel9@sha256:a160d7e384009b5a52c49c331ceb5e7661402e5c423ceb44b2ef33c1b5c1dab2
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:bac899e0a4dab6887a79b05301054f5f97f3fe847f69c23ef7cac72e7380ef94
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:bac899e0a4dab6887a79b05301054f5f97f3fe847f69c23ef7cac72e7380ef94
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-proxy-rhel9@sha256:be9b70a5bcb7a3d40bf40737795bc531fdce2cbfb3c6a0db74c5edaa3108832e
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-webhook-rhel9@sha256:9928436c3fa35a8915cea98447882d7577e3ccbd4cab6e8f767976123e0faf13
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:28b342aa763adbb995dab6c4d81e38d470f832cb9254c66a976ff024a6a51a4b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:28b342aa763adbb995dab6c4d81e38d470f832cb9254c66a976ff024a6a51a4b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:28b342aa763adbb995dab6c4d81e38d470f832cb9254c66a976ff024a6a51a4b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:28b342aa763adbb995dab6c4d81e38d470f832cb9254c66a976ff024a6a51a4b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:28b342aa763adbb995dab6c4d81e38d470f832cb9254c66a976ff024a6a51a4b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:28b342aa763adbb995dab6c4d81e38d470f832cb9254c66a976ff024a6a51a4b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/console-plugin-rhel9@sha256:d7721f5c3c7ed4bc0a0961e2c4b5ec3416d62e5cfbd2704488e063b22c23a141
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-bundle-rhel9@sha256:a0d0d2ecb6df99708125b1550bc7cdf30f872572aea11d25775ef67d90bfb166
