versions:
  current: 1.20.0
  previous: 1.19.2
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.19 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:10fc3f9479f312320081e52dc692de3faca5cdd7745c1c837b75571a38093185
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:c486a2b4ff8cfd685460e5c5fb31c8bdcc57f503b9753d9808728e25e7b5c050
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:4cad26651eebde7525664ea7a02ef1d8c085d09adf7eb56f01637bec9cb8e6da
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:4ed10de752d5a2442fb5b5d49a67ca1a262e25186457a66b970cd0a041746e1e
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b2108a3be45a500be6b55cc41aa982b99fbcc4c1a26b20969824083732d67dbd
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:98b35f95bbda2530a25bdaee9c3fa3d0861ff54f4d8f218061be3ec564a0b385
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:4538f5f017cbf9b9d16b0be98038a8b25fd438012c438a984f65b5a6614d87c3
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b2108a3be45a500be6b55cc41aa982b99fbcc4c1a26b20969824083732d67dbd
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:34241d2518649dba3012348f8b458eebc4f851dda123a8a0a20d1e22a7e07540
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:9ca77f259ae0ef65cc5569d9bbd992b0f5d1b556f0540eb958b5cbd334b5b52d
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:8f1f83eb5b7a245e6072cba7f7e9e5313a7edf751fcd459264514ab6bd382473
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:41cceaf38e404dc99bf4c2c525ff6da10b3e41e2e310ffd0ba5268a18b8dd395
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:ca8e5a96a8a5eae28b38873583826c0043111484fade6794116ee1c7c9a0e1bd
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:8cdb90416bd937366ee66fb2eef8551f257c68d8446a3d4da3a38b768df93d7d
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:f7c010493912ebe919bb4ef70231f04e07cbfe6a44c85d0636b2e8b3297e649e
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:25483862e2ca59f046a450efad3bb24e263f3a072d107621d7e71ef214b4a26e
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:bb2a3e9552c91d3db52696bcfca7d99d6b176dd5847e23b290f9a52bb4d51c36
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:04fb96cdebf972870da01d717126d2a6ece0f626109faeceec4ca964137745aa
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:81fef46682555c85641152b4dbae40e62727e06d2da59c61df91414196954bb0
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:2ddc10c9b05e1f0a88d1f8771c42eb917bcc3c6a4dc3478a9019b6b631569838
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:0203a8618f35af26b006f4c758b0d46a6b8ba15c55e21b7f32b96894780f2ea7
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:0203a8618f35af26b006f4c758b0d46a6b8ba15c55e21b7f32b96894780f2ea7
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:0203a8618f35af26b006f4c758b0d46a6b8ba15c55e21b7f32b96894780f2ea7
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:e3807fc0232be95b4a353bfe88d4bbbdc2f238b2eaa2c0fa9284d2814354a991
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:9097756d64b30c9f656334e05e5e66d24d9b7a9d6e2c26cea62304cf4e2f5826
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:e55958bcb03447b9cff88dd459cd4429a84932f0b4fa4dff8d0c23e74607064b
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:c225d925ed76b890aecfd6fc9c0f0c9fd556a0208f24df6a8013ffb486a85cb5
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:04c9eeca0add477def3af0317405f3c6d0f801d3ce9c369985ed77f8a519e705
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:5993047fabedae3d4961798546137de9ea5ebc26575043c868f8392991d213d8
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:22e7c2bcbcee756e52d50619715a83c2388358f50102946010c95a06aba042b6
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:22e7c2bcbcee756e52d50619715a83c2388358f50102946010c95a06aba042b6
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:087d2e2dbea6b347d9fc9c2351f531c5d943a1f974ede8016522a0dfd1193d21
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:9428a3a0ed2b27aec189f2dd7136d68c7b694570d50f13fe1552f2eebcd5b314
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:4635962307e3f24a65c05a8ac2feeb465208d37a2306a23f1e6448d9a2cbd9ef
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:4635962307e3f24a65c05a8ac2feeb465208d37a2306a23f1e6448d9a2cbd9ef
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:bff455112443bd20c97e5c44f213f56ed726ee3039cd7ae478691e046ad3c5ab
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:bff455112443bd20c97e5c44f213f56ed726ee3039cd7ae478691e046ad3c5ab
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:bff455112443bd20c97e5c44f213f56ed726ee3039cd7ae478691e046ad3c5ab
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:bff455112443bd20c97e5c44f213f56ed726ee3039cd7ae478691e046ad3c5ab
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:bff455112443bd20c97e5c44f213f56ed726ee3039cd7ae478691e046ad3c5ab
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:bff455112443bd20c97e5c44f213f56ed726ee3039cd7ae478691e046ad3c5ab
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:d4ed5552735e28fb9b3821853821a191f68a7f8d31aa83cf2639ddb769b6342d
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:ea8d23c0f8a937ecf4342996f7b61d57060d15e6a3b46b8a12bcaa126dd1cd59
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:a971140cc3e047004b7f4df849433673930ee4d8cb3ccde9eab8e20bc9ff397c
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:75511324f047980a24b29d990b23ed0a6587d447e3ee37e22a386f559796c12f
