versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:16d7044021bbe6c43dbdeb042da7a08bb00774d02bd3adcc18b1b45ea9932aa9
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:c378d7a6c684d8377a27f3cf650988a3c0c48b45ec53a13823e6dbe70a7ee39b
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:ecb1b3dd4e7f85fae4f6fe71e6584f13d2ac28b2de6fccf79fcb15bc7911eec0
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:7d1e9a451ac16623893467950e08ed00bcc090e29e5af07a5af10545cf3419e1
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:9046368a77fe00206f947146b052fdf188623dc5889fbc0aa0df8927dafbb65e
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:66f7cecf3c8c9b8fe1bfdc1c4a01ab77fb9b23dcb2552afad86d362c24bbfccf
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:c03b3ede481c9a336b92c0b3eb5882bb812990067da3a709051725797ec9e7f5
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:9046368a77fe00206f947146b052fdf188623dc5889fbc0aa0df8927dafbb65e
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:767a85aa9edd9a8091143533add919f91377936fadd2b067de649190a3ffc0a2
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:0a9198a159be295785f8b3b9d38973c0d6d32a6f53530c5321c0f2866325aa58
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:a06a3041bea1ab000d9ac26d85f8bad6d536ccfcc739efa86bb7c485c496f7ab
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:1b4d8cd8519508dab88cdfa2815fe54cbac27918bbc69fe94d0b1a16f434d9d0
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:8941ddf8e8129f85ef22a7173d1d40e6488ac664cb79bf252c1c1dffa6c86b7b
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:6f4d34a63d14299194679556e94be16b58c29f8f20af3349b1eedca35aa7397f
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:a150b87ba498ca099b9c4c92ff893f9e73945f4988d0eda47f14e1dd40d0ac35
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:0522bacec56b3cfe4f6cc4fed80e144213d4582019a716cf0fe46bbfde1e843d
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:5a6bc4b66cfd1be44d01c11fb2903d77ecd69001b1083972cf3643484f0f76ed
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:abbafd605568e5b374c9cea969b2f2302759ad6b372988d2bb0f2c7ac6e0e8d2
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:ac004e86d181642b268deba990f2c2232ac577c138a570747ed16ed13fe94b9c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:84bf80273fb3ce06a9882014ece9d21be4f06209bf395289b2ac12cab7d5fd04
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:8e877b845f8e8895ce0841f0a5a4a3d320f9aed11354e7a1995cb797a49ea6b0
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:b8c6a292084db236cce68e6b6824ca3547dfcb1239e8a9849d951bc6c260d6c7
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:3ff0097701fc6e1de5edda5f7c0066249273bcd705aec77d7c5dfa521648b89f
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:82481553caebddde61c6c1adb61306f17fd104cd126a02f095704b563c55c5d1
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:66f8c53b9c4d6afc2af8d4ea84e530b5339a9f17bb9266bec4e48ed576fc0598
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:db839c8b305785eb2d5313a195ab5f6996c5b8f3fb97d317dfbb0e3ad7b03375
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:977fd2d48245db7285e4e65e8944d1c127975bb4446c62934bd34e3f3d62618d
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:adc010c520645982b711031d300c3905291a3c3ab5344fd54397832ace672ded
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:4bec53cb6db4e6b5eb1668af71e32ffc22d83837435e8d80011c212f59f6a543
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:a64325578085d3a3ecb188343c7491f98d2bc3c06d932d7aa990d87a13ee772d
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:7497dd80a619eff70d1b52c038290e43cebaf1bd69da5773455942fd24a56817
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:0f16301424f4a0ffcc498cb08fa45cd495bb663382e30132744754da0dc61c43
