versions:
  current: 1.17.2
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.17
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-controller-rhel8@sha256:6e21b599eb81e08d11bc4b33c23298649cfedca212686049697b098ab1a19895
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-webhook-rhel8@sha256:3f1aa54ceca3b37d6f8f53510ca27a914dac17eea3eb6aca204c97518e71d9ef
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-resolvers-rhel8@sha256:4d0398a75f30dac089024a023b576366210a24e1b0f07f57b2f403b2af3d40fc
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-events-rhel8@sha256:37ec60e40b53a6574deb3af45caf1118fcd5c723d761ffad042f79bf8b439c35
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:24c0ccc8abfdb1a8794a588b9ded77785f3097554839d4ebb9365cf7f5ded654
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-workingdirinit-rhel8@sha256:631afccdcd5420458ec5dde02811e6e5fec27b35b13ff2548f0c6809b70e4331
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-nop-rhel8@sha256:f02b5300e495f05df96e9e932145520348e027703182eefe71bc25c241f13c71
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:24c0ccc8abfdb1a8794a588b9ded77785f3097554839d4ebb9365cf7f5ded654
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-sidecarlogresults-rhel8@sha256:1ebede194625145dc2a2ec09555738d70801242a2afea2be7a0e030871c5fb1c
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-controller-rhel8@sha256:650391ffd3e4c7b173bf9d718405b2375c6ff2027abc0b7ce4f67e79e7ef4b81
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-webhook-rhel8@sha256:922b9e86a674a6f3eb82f510569ab9cde97a1ad833c263335cd4164bf4164b66
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-core-interceptors-rhel8@sha256:7abc88bea01dd6513f6e48334f0b98501f909a1dc1ab9e83efeb3c1a834f8f92
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-eventlistenersink-rhel8@sha256:4224040b00cfd76e85f80aecc5095098564cc62e9c477fe2f7a428b30df7d4d9
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/chains-controller-rhel8@sha256:c79583691dd60ba19f8b580cc94137918481c0ddbbbdac9bde7d8b3382e4423c
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-db-migration-rhel8@sha256:f4bb78d772b6b6f13d8f5b5ed7ddc3ca01590332d621f1364c428a3255e20b45
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-api-rhel8@sha256:d0471bf4cdeedb82270910fc357327f22d7590de2dfdc4d87c83568bb9fc1f37
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-ui-rhel8@sha256:59c2d69aaaa8e6beb7b1dc373801b76c57699302c19e083205ffd07c9182c7ee
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-watcher-rhel8@sha256:647905e58fb5e074b5dcf73cffc954c26c04e925c56889648e3a5b68081eaee4
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-api-rhel8@sha256:3792a6967315151925fa0bb02fae8bfea6bbd703230fc2dc56b1235368c2ab46
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-retention-policy-agent-rhel8@sha256:b5cceead6b8e9c99655c9ba810679b9d6fb978e5ff18d020a46d475c4c26fa29
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:ebcb21e359de2b4e3a652930c67a1f4d5e8b03df5072de8e6158f14aa2c31ed6
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:ebcb21e359de2b4e3a652930c67a1f4d5e8b03df5072de8e6158f14aa2c31ed6
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:ebcb21e359de2b4e3a652930c67a1f4d5e8b03df5072de8e6158f14aa2c31ed6
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-webhook-rhel8@sha256:9182eb580a4c8ceb981781516dbcf7b2736da0c26d04938e345dcceed6c52178
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-controller-rhel8@sha256:decd4fb592accff66c1c607f41a03f8a4e05c5de7e2d8ab135f41793ae0722c9
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-controller-rhel8@sha256:e9c85571cdb30e1e633f66be91eea50c07b4707d1bf27258d0810b8644a0e9d4
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-webhook-rhel8@sha256:1d6bb429835f8b4068850ae73adcb238c87f3138ee6960d8fd19d4e3495bcc49
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-watcher-rhel8@sha256:9fc650af09d1e0b9d7059173b320129010a4e81915c56da969ed2c7587533c16
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-cli-rhel8@sha256:7f6d7b1878e17ace11f4d8f6261eead82bbd2c46e3f5341f756c0dd5a57b14eb
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:4f445671e6fabfeeb4de656b29534bf5c751104942935eb7cd597b9210e107e5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:4f445671e6fabfeeb4de656b29534bf5c751104942935eb7cd597b9210e107e5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-proxy-rhel8@sha256:9d00cd23e3ae63f3c065869e4a3b43c722de6e02d2e198a5f3b8d5128d9d0c64
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-webhook-rhel8@sha256:4bc7f1bf6cffab52b3ab9a9e24852a2ebec9058fa2a1c4ca42dcc0ab04e2715e
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/console-plugin-rhel8@sha256:47e97c124b89a9cb6b98bdca3987e2ce89f6ee22fe499cfef817e18fe451b649
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-bundle-rhel8@sha256:f2162408b5b02c6b1c819c1ec18f1e2c4e8a97e9271545ae4f8ad6dd18b42efa
