versions:
  current: 5.0.5-593
  previous: 5.0.5-592
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-controller-rhel9@sha256:975564e09acf1c0c633a25afad21a375dc76480f69252df3fdefaf8b77db8f60
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-webhook-rhel9@sha256:435c4458f231ebec222259f553153028fe6e7e9d33c64538de3a4d6d4d32bc16
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-resolvers-rhel9@sha256:c272494d7909e54cd2c1e8e5f2be9bf001149350359035e7881aa8aaa6b5911c
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-events-rhel9@sha256:086fa3bbd39671366c596f24a0738d1f846dbfd617f905113e38c62cd902f7e4
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:d55a5d9a932cf678aa809a1bc58e53fdb837ad37c2dbf2fd868ce8489fcb79ef
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-workingdirinit-rhel9@sha256:d5cbcc13fb834d7c45bb3884776ec12a9c9a9a1d3303f704d17d5d0688639f4c
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-nop-rhel9@sha256:a40fbb568cf524ddb3e9c6fae2005748064c1ec07b41acfa6e3d55ad24290579
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:d55a5d9a932cf678aa809a1bc58e53fdb837ad37c2dbf2fd868ce8489fcb79ef
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-sidecarlogresults-rhel9@sha256:396ef62cdca69ca0d62cffc2fa0577172398ecb5cd9540b33ad7aaf1ceb98b4e
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-controller-rhel9@sha256:284c4d47ee99b043c3d1781e58cf5fd07ff4f10fbca80be9cf261f75ace78cf3
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-webhook-rhel9@sha256:e00512bae975b88a4679676e424b6404c19bd217140bc7242cbbada207be0bf6
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-core-interceptors-rhel9@sha256:a5b87b0cfacbc4642f9bc27794ad75a93e4e7f180a10be6613efdaa8d00fead3
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-eventlistenersink-rhel9@sha256:983ad7cf0bb682553085713190f9fd07b2a2a429361f8e22b81ca8d7210a4be8
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/chains-controller-rhel9@sha256:bc38da6e7e3a38d22078a05d76c124340e2e7f58736620d6262dbda9c24b3765
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-db-migration-rhel9@sha256:8f9d4e51ea20705e2a2f1607c6313056a149074b183ca1eacde6056d9ca28d01
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-api-rhel9@sha256:124dbfb41c08500c84988e2749e8dc9e7b586d21192119e42afc48af0f0fc856
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-ui-rhel9@sha256:cdf80ed9b9a7daf2a35796001099cbfba396b28997d4be8aa62064aff970deec
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-watcher-rhel9@sha256:05669a89d9519665a9230f797a79ce579e443dfece2cd55b90c57f9317d10506
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-api-rhel9@sha256:e096db5738f4a7748bc739cf788e60f9ded21d1055f6934aa193c0d49065f382
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-retention-policy-agent-rhel9@sha256:f627477cff2b590b299dd9eafe76af28891d954e22a87d5f2c6a844d30eab5b8
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:afad5f9f03664ffd5a2b303c6168ff3a3c54cdad48cf890baca4adaf3bb8d301
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:afad5f9f03664ffd5a2b303c6168ff3a3c54cdad48cf890baca4adaf3bb8d301
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:afad5f9f03664ffd5a2b303c6168ff3a3c54cdad48cf890baca4adaf3bb8d301
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-webhook-rhel9@sha256:32416df654c142f9f5ace228c25eb6f0edc9f1aa49dd55caf65d1a4102e722b4
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-controller-rhel9@sha256:0b53c52e0491d1c3d229c0140f174be3e2339cf6caaa043ba13f18806ce2d10a
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-controller-rhel9@sha256:e41625f49eed20f7b3207e02c1c6de9028ebc8de1f951202e93fd6eb7adf7949
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-webhook-rhel9@sha256:44342dca036be7ad4dc451cda6c722518211d3df8c85fb66bdbbfc42d2341848
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-watcher-rhel9@sha256:ccc1c798edf8800ddd5b0e72abb518fa1b1a64bc1e8d209a412bfb65c7d16933
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-cli-rhel9@sha256:a160d7e384009b5a52c49c331ceb5e7661402e5c423ceb44b2ef33c1b5c1dab2
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:048f0901de786b84a38314b6afaffc155908648de83befd0e59b7a0401ae331d
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:048f0901de786b84a38314b6afaffc155908648de83befd0e59b7a0401ae331d
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-proxy-rhel9@sha256:278e42540144ef5613153c15b5abc98aca75ddef5b9be6dbd21949039db4041a
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-webhook-rhel9@sha256:5a2adff3ca92c5d3a8725fc95e5c70f941d1efd392194b151747c31989b582a0
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/console-plugin-rhel9@sha256:d7721f5c3c7ed4bc0a0961e2c4b5ec3416d62e5cfbd2704488e063b22c23a141
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-bundle-rhel9@sha256:ba0803727eba2bf74ffcc9e3f21eeb455ee46ebb994e87501b0d6b18ca7a80a6
