versions:
  current: 5.0.5-593
  previous: 5.0.5-592
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-controller-rhel9@sha256:03c644a7507caca50f261812d69d8eb7151809a9cb9b5139c602202578d34cf5
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-webhook-rhel9@sha256:ca39efa5533827102f2b848aa64cd5c91691972e853b5ce17ba6a42744e88498
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-resolvers-rhel9@sha256:cbdc3da63a722ccdf58eed3c9ec84e7c0fda1855b5b92823e8cecc2ab2352ff5
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-events-rhel9@sha256:b0273785472a1eb7349a2d786d36a666cdd806be8f14ccc541ce64c94592494e
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-entrypoint-rhel9@sha256:716fb0ed722d220942919c6f1a81139bb06636615e79f2d13faf2cdea63130cb
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-workingdirinit-rhel9@sha256:93c745ce3e446b753c4e917b6756c551222b2649adf7b524e72e5ce44c738ed5
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-nop-rhel9@sha256:0252bf1a68b99988f5a48b167a69129334c40e6cfb3de643a92398a11915ab4b
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-entrypoint-rhel9@sha256:716fb0ed722d220942919c6f1a81139bb06636615e79f2d13faf2cdea63130cb
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipeline-sidecarlogresults-rhel9@sha256:c7cec6ce89c43b155812d718d6fc253c5f6eee38f4d622d10d9939f66b1ec5f5
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/triggers-controller-rhel9@sha256:6dc8c42b8cb84974799f1029351d848a49855315361c16df9966b491ab7a9ade
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/triggers-webhook-rhel9@sha256:3002a79837da2368ca37b240fa1dd1783840f2d39a0f9a0188020a2b64c062fa
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/triggers-core-interceptors-rhel9@sha256:7a3b59bdffa0afca7eda0e38763f241338a095da9953d47ac4c04ebcf970979c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/triggers-eventlistenersink-rhel9@sha256:46521934431705d6806dd366fdd37ec1751dd0f717af0832246f078e3e98e419
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/chains-controller-rhel9@sha256:d79ecf761eced88870a7f8da67e49bb5087454f2d04d80072559e0465efec72d
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/hub-db-migration-rhel9@sha256:36284aac370511d868ad47c2cf8be0bcf33a8c66a466ff927059701c53e6a4ca
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/hub-api-rhel9@sha256:cade111440f4d0227b5135fec32e4b6e4c4619a1589ac091f28753e8c3088cd4
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/hub-ui-rhel9@sha256:d057dcd674f926e5c8559ef48d4d057f14337ea82e6c3b770d60de4563e0aa30
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/results-watcher-rhel9@sha256:9799df18b67eb4fca1db11fe303607bffc9747625e698b65e3d34c3d40fb1f35
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/results-api-rhel9@sha256:223d8983b60ea443891e8012e3f47a9de2d64e67d212f53b33ab4832fb93055c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/results-retention-policy-agent-rhel9@sha256:5fc60d22be552fed1b62b0afd062264393e181ac34e69404d68b614c5ddb0ac3
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/cli-tkn-rhel9@sha256:6c120617db5240941920b1811f751449ca6d926399590f1972a8750dffaf38bf
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/cli-tkn-rhel9@sha256:6c120617db5240941920b1811f751449ca6d926399590f1972a8750dffaf38bf
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/cli-tkn-rhel9@sha256:6c120617db5240941920b1811f751449ca6d926399590f1972a8750dffaf38bf
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-webhook-rhel9@sha256:bb20979bd1b418e5d1fe8776c7508da95eacc18d34e27e759b56bdec5a8d9823
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-controller-rhel9@sha256:ca747c93ed4ac2175652f5a2c2d03e42c179863c7ea41de935ae1b77b7a127d1
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-controller-rhel9@sha256:183c022418e1da066cea584f4827dbd665a5defeecf98fe0f74467571e9f05b9
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-webhook-rhel9@sha256:fe46375475fb4f15ff68e279de9631cccd84718163d217c2a1802c2d9768729b
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-watcher-rhel9@sha256:65ecc2c0f0ae6a3ae47bb39207d5616064a2bb727f13201e8742bdf43ae20dde
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-cli-rhel9@sha256:4215f2a482fa99a1a07c317c879f330320af9252980ad71621f4681447b0da0b
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-operator-rhel9@sha256:e7a95053e5a8d37f2e07f9e43583f0eddbd85b5c4ec5cd83d9519c253e7a4140
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-operator-rhel9@sha256:e7a95053e5a8d37f2e07f9e43583f0eddbd85b5c4ec5cd83d9519c253e7a4140
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-proxy-rhel9@sha256:89ce38e676722356a8441b7837169ba7435d29a50c153066818f219bee027633
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-webhook-rhel9@sha256:b9f39d17cf4a6ee3c14ed358824ebd95f428c9a5d95505885ec2893d04d1b00c
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/cache-rhel9@sha256:de54c42aed788d6b05068d8484c45502ca50c11dc982258cd0e55c8e93219973
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/cache-rhel9@sha256:de54c42aed788d6b05068d8484c45502ca50c11dc982258cd0e55c8e93219973
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/git-init-rhel9@sha256:b2c18a0f8ca26eb1babbf20769d95f8221e749ecfa14c5b5d4ad8f83fe267c02
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/git-init-rhel9@sha256:b2c18a0f8ca26eb1babbf20769d95f8221e749ecfa14c5b5d4ad8f83fe267c02
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/git-init-rhel9@sha256:b2c18a0f8ca26eb1babbf20769d95f8221e749ecfa14c5b5d4ad8f83fe267c02
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/git-init-rhel9@sha256:b2c18a0f8ca26eb1babbf20769d95f8221e749ecfa14c5b5d4ad8f83fe267c02
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/git-init-rhel9@sha256:b2c18a0f8ca26eb1babbf20769d95f8221e749ecfa14c5b5d4ad8f83fe267c02
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/git-init-rhel9@sha256:b2c18a0f8ca26eb1babbf20769d95f8221e749ecfa14c5b5d4ad8f83fe267c02
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/console-plugin-rhel9@sha256:d53b03a53729a852e8a1672fa04982e8708fdf492a877e1548ae7b1202c269da
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-bundle-rhel9@sha256:e27769ecc6b6d16e8f62922a0ad4c3cb684e3a72c2f30baafe4d5a4187ceefac
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pruner-controller-rhel9@sha256:37c3072b91cd660203ca45cb9f379e0f09418bb77e8dfce2d116be5937993ca4
