versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:f0cab125777c084d4a808327aacdfa6b79d2a1a47517a2ae87d4aceca9d51aa1
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:af39846cfc8e20b7285bedb3cf92e7addc9150abc4b8d048fe3ff8654e94bf1f
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:c8c6731302a447c4ddaac6f47be6f29309f0238cce18351c9b898f633be39269
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:9e93d352bf54e469dc6cf70b8974906133859c771607ae6bdef8b93ddfa95ba3
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:a3d7269e1be4216c4a2bfd70fd4a18f8e5e7936ce8ba7b992a81bebdb46545aa
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:75134132f626582040168fcfeb85241b4362466a93a80a97b9fa2097b12b7beb
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:6a26c835f21e4165f89c126485e85d7c12ba2c430722cc3550ca7618d1116540
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:a3d7269e1be4216c4a2bfd70fd4a18f8e5e7936ce8ba7b992a81bebdb46545aa
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:cdf91e123cb9209d308d22927e454834b819b5095214b488bc8dd4c423cc34fb
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:a8c4dcbf338ce195f6487bd534fe8a32ed14ed50826381af9f7b78e39e399d85
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:6ad43ada4ab734381ed6eb3a20d818ec7d376dae5b45b49e6e550ad170afc603
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:35552d8d69e8515753a737c3cdcc09a030fc93917257257f51719ed887483c5b
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:4a7529a7f91dbc85b77d0a1b9bdf1cd2d0b4ace9b137d7f7cc199c21dba4bc88
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:20038e2bb5ef012c6cc9c3ac1c8ec823189734f9c81e7afc5c9ce124d26eef67
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:07a740e6b8d5c71c0f1c0cca366ac62aaa42b0ae2647fec38b82514859dcdfa7
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:5b3fe070ffa0618527c8910c46aac6698fe485e71c93e37e88a6f8dd193d4f57
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:e487033dd5923001566b2b35f86f074e9f57732cf050cd0c8c14969047ffaac8
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:906af1517db0a4a6e3b2540f69de9f89c94c6b390b96cd4084f84ab8f87193ae
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:185bf0baeb1c4e3ee9f846b0ff1d6c2439c637f0d8f07b6a86e71f811c3161d0
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:ce75b106a5ee86bdf77a27ee35ddeaf56560eeaa2f845fd997fbe1ba48bc35f7
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:a032a55f621962023b069bcd04b9ca5913af9949bd79d5a44435d92fc240c6ad
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:a032a55f621962023b069bcd04b9ca5913af9949bd79d5a44435d92fc240c6ad
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:a032a55f621962023b069bcd04b9ca5913af9949bd79d5a44435d92fc240c6ad
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:906dfd12dba6aebd255ed89712535e178ee2b134cfc13b60aa51c760a05de0ff
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:b3bf2bcaec2d994f700993aae199cacbc70a6881371b2afc566f194545e544b4
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:397393c99e14f7837433426561137e29deda192b25303b37db1d537d6f83a2f8
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:b9d7c14cb936991e57b88c8add96e4315e87b906a77b80188b9871db0661e135
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:af2329eea0532f39da4a367b86b7708547965031b578f4c14b6d970f33f9981d
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:56afeb4cdf6cb7188a5af77d7eaace6d499d7c977e96e644890f91eb8262c65d
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:e9e08cf295afeb5a1f02eec4fac848d25a00f6e86d74c28f2977ff0456852249
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:e9e08cf295afeb5a1f02eec4fac848d25a00f6e86d74c28f2977ff0456852249
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:b6d8df460c66e35701893823e070ea8c856d34fd7ff2d3f2009a5585a2c44087
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:d3f90463d9dec7369c74444d3e7074554fad3443353574ab9bce9dc5c3df5166
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:992988511767f1ca0fe9352cbfd52e20c2a4db8757abb9532dada605f436adbb
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:f96e2c2f81a30575c4f7ce869587b1489cb847d41c8c5e73b4dfb1a3bda71165
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:7497dd80a619eff70d1b52c038290e43cebaf1bd69da5773455942fd24a56817
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:814dded254545447356de82d3644b124329fa61c63be7b2cbf8722ceffa47e1e
