versions:
  current: 1.14.6
  previous: 1.14.5
  previous_range: 1.13.0
  channel: pipelines-1.14
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-controller-rhel8@sha256:bc37f5cb6727181fdbab9f9407c3c327c62b329436ab46bb4c5e65413270edef
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-webhook-rhel8@sha256:3f1aa54ceca3b37d6f8f53510ca27a914dac17eea3eb6aca204c97518e71d9ef
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-resolvers-rhel8@sha256:4d0398a75f30dac089024a023b576366210a24e1b0f07f57b2f403b2af3d40fc
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-events-rhel8@sha256:73387bd5095950fdfc43e2b2748976a323feb9588073569d539d3fadc822a268
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-entrypoint-rhel8@sha256:7eedb956fa04be25fcc837b509cfb59ff8a2e9df1078946a80e94b53f70ea249
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-workingdirinit-rhel8@sha256:77c74e80ba105a609cd0356db98d073c367aba8d167aa4856bb3a9297a497088
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-nop-rhel8@sha256:534d8633c7a3f40726e33f13240d2f056598ae66d9a2afcc61ee4b94f740b37f
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-entrypoint-rhel8@sha256:7eedb956fa04be25fcc837b509cfb59ff8a2e9df1078946a80e94b53f70ea249
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-sidecarlogresults-rhel8@sha256:675577dcd35c9c14e4fe3f3b15a54ba43486b6e6e10a3e4f321ef000be059a3b
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-controller-rhel8@sha256:b63f90abe58279fcd9a020f14d9ce6eaf7886b992f3062fc74057dcac9a6ff67
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-webhook-rhel8@sha256:246fffe0d9512290766d2dca10e8f902afd97efa3690cbe8c244879110546cc2
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-core-interceptors-rhel8@sha256:be2618b44629c840e27390e31ae29cffeaa48daa1af9ceb288aaf65f9baf308d
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-eventlistenersink-rhel8@sha256:a24c63bfba5a8d09103ccddfab6398d39414635d12e3f8a7be96e3f953788b3e
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/chains-controller-rhel8@sha256:c79583691dd60ba19f8b580cc94137918481c0ddbbbdac9bde7d8b3382e4423c
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-db-migration-rhel8@sha256:f4bb78d772b6b6f13d8f5b5ed7ddc3ca01590332d621f1364c428a3255e20b45
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-api-rhel8@sha256:d0471bf4cdeedb82270910fc357327f22d7590de2dfdc4d87c83568bb9fc1f37
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-ui-rhel8@sha256:59c2d69aaaa8e6beb7b1dc373801b76c57699302c19e083205ffd07c9182c7ee
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-watcher-rhel8@sha256:647905e58fb5e074b5dcf73cffc954c26c04e925c56889648e3a5b68081eaee4
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-api-rhel8@sha256:3792a6967315151925fa0bb02fae8bfea6bbd703230fc2dc56b1235368c2ab46
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-retention-policy-agent-rhel8@sha256:287495f064c313e4cd913839718b769a516029ebc752955e6f98689fbc12ac9a
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:ebcb21e359de2b4e3a652930c67a1f4d5e8b03df5072de8e6158f14aa2c31ed6
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:ebcb21e359de2b4e3a652930c67a1f4d5e8b03df5072de8e6158f14aa2c31ed6
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:ebcb21e359de2b4e3a652930c67a1f4d5e8b03df5072de8e6158f14aa2c31ed6
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/manual-approval-gate-webhook-rhel8@sha256:9182eb580a4c8ceb981781516dbcf7b2736da0c26d04938e345dcceed6c52178
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/manual-approval-gate-controller-rhel8@sha256:decd4fb592accff66c1c607f41a03f8a4e05c5de7e2d8ab135f41793ae0722c9
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-controller-rhel8@sha256:e9c85571cdb30e1e633f66be91eea50c07b4707d1bf27258d0810b8644a0e9d4
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-webhook-rhel8@sha256:1d6bb429835f8b4068850ae73adcb238c87f3138ee6960d8fd19d4e3495bcc49
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-watcher-rhel8@sha256:9fc650af09d1e0b9d7059173b320129010a4e81915c56da969ed2c7587533c16
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-cli-rhel8@sha256:7f6d7b1878e17ace11f4d8f6261eead82bbd2c46e3f5341f756c0dd5a57b14eb
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-operator-rhel8@sha256:4f445671e6fabfeeb4de656b29534bf5c751104942935eb7cd597b9210e107e5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-operator-rhel8@sha256:4f445671e6fabfeeb4de656b29534bf5c751104942935eb7cd597b9210e107e5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-proxy-rhel8@sha256:9d00cd23e3ae63f3c065869e4a3b43c722de6e02d2e198a5f3b8d5128d9d0c64
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-webhook-rhel8@sha256:4bc7f1bf6cffab52b3ab9a9e24852a2ebec9058fa2a1c4ca42dcc0ab04e2715e
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/console-plugin-rhel8@sha256:47e97c124b89a9cb6b98bdca3987e2ce89f6ee22fe499cfef817e18fe451b649
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-bundle-rhel8@sha256:f2162408b5b02c6b1c819c1ec18f1e2c4e8a97e9271545ae4f8ad6dd18b42efa
