versions:
  current: 1.18.0
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-controller-rhel9@sha256:4799884fcf1edf09954d0d278bf726ff4e4a30cf84f9d1b1dc2c078bc01f6154
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-webhook-rhel9@sha256:e4842ed74ad57fa09f292b9600efa1ead65fd74149bfd756daaaf56bb971413d
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-resolvers-rhel9@sha256:c674dcacd4ff3f6769773708a6f54fd8e21349f6a0660df6225327415af0e7ed
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-events-rhel9@sha256:ccba273e1e8431dae1df8b200c637b9de4162f6c195eb8949a996742f54e0a3a
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:20258e7b1dc3d9bd3386bc3569b11952b9fd72c6efc75f992d2fbca1f648d1d0
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-workingdirinit-rhel9@sha256:78fa74448ff0de1beab8a927c64722ac636d407893c24e9b2da654faa046605d
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-nop-rhel9@sha256:19ef8b61c1fb394c60378e54ffece84ee23e0c3c8b2d72ebff4e826e567dc042
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:20258e7b1dc3d9bd3386bc3569b11952b9fd72c6efc75f992d2fbca1f648d1d0
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-sidecarlogresults-rhel9@sha256:28f247a78b548b41f702d5c54ca72222e6cc08979eabe5c5c82444cf52d868b5
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-controller-rhel9@sha256:6716df356f1c4d412eb210eb6a379b7d6535a320ee4af189998abf762064aba0
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-webhook-rhel9@sha256:18f13d36a3b6ee45909df9061dfc1c4c6dc8c166e648270da5457499c58b4793
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-core-interceptors-rhel9@sha256:d4adf21adf9aff676c9d3f1cbfab1d6bb2782a9c1b29cf5454d361b983d79d94
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-eventlistenersink-rhel9@sha256:fcdbdd5d770ad00a8a869f11662ad38bbc43641271f389bef4c1147e748b5cbe
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/chains-controller-rhel9@sha256:2595a86cb4837430c4ff87575357f6f9acfe68d75d7c24c115cd23c37446124f
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-db-migration-rhel9@sha256:d0700e9cf7995d1351b0027d7694030d2f23f76250d6cd0d35918c098c3ce4f0
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-api-rhel9@sha256:c9461040f49b5c2c462d76e378a0a3238e924fc51c33c7632bba6671986d768e
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-ui-rhel9@sha256:3a62b233c05f3662222c9cbf94e4e012164e1d6cc0e8c8ec5d52617ff53f33ca
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-watcher-rhel9@sha256:fd0c16e29734d91cc23752608adba3880e1b3209636a895bef2229dfd1f6ac60
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-api-rhel9@sha256:29a664124b18e2f924c4c42213d2f5e35a2596e4ecac276b8fb27794cf66c621
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-retention-policy-agent-rhel9@sha256:dc275d2e3d57dbaf092f2b1dc2d80806bf7e0d3b8f5774da58b5f9c68877d82e
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:e2deb456822ad7f6db13f05fdbf94a829b87ee281e98dc0d80d245030d5a2958
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:e2deb456822ad7f6db13f05fdbf94a829b87ee281e98dc0d80d245030d5a2958
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:e2deb456822ad7f6db13f05fdbf94a829b87ee281e98dc0d80d245030d5a2958
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-webhook-rhel9@sha256:f2b741e1385604274020cf7f6855ff7ee13bc513d59cce0b7ebcf3590e54178c
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-controller-rhel9@sha256:11bd27fcae01cf1ce8c4f04c029a583ee929c5da25e67d1d589e18d8f518b1a0
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-controller-rhel9@sha256:e8a5ba839496323bf5709b0f5b0167dd82cec4c9077c9ad1cd8c72d062e71061
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-webhook-rhel9@sha256:1f69b4b323203effdf51b4fbdeb27799028d2b2661f386bed39091ab88fd84ea
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-watcher-rhel9@sha256:76273678c956e94e4c95ff9da5840dd0603a47faac6447c058b99025d62c5266
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-cli-rhel9@sha256:8efe03f55d93f5f5c8a43b87d530265aa04e8bfde7bc38ca4ed14cc257e25889
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:55772e5da79297ae70595b74425c78e04f8727d2af726d2556006b64aae2922b
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:55772e5da79297ae70595b74425c78e04f8727d2af726d2556006b64aae2922b
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-proxy-rhel9@sha256:08e16bd1724f2ea542b3569d101cc3568ff9b0173fdfaa4360c4224fc6f555d3
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-webhook-rhel9@sha256:67096815ebd0e4c4c82577bc405a7827633873364c1fae1531a4fc4a2e6d4c5e
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:d2cf3f38ee11f0e1442638296f3d77817069a48f645bfc01728ad001e14488d5
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:d2cf3f38ee11f0e1442638296f3d77817069a48f645bfc01728ad001e14488d5
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:862da2865b990060330346d3e11b41722849d9d5c7bb7c149c48c2f782b35657
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:862da2865b990060330346d3e11b41722849d9d5c7bb7c149c48c2f782b35657
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:862da2865b990060330346d3e11b41722849d9d5c7bb7c149c48c2f782b35657
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:862da2865b990060330346d3e11b41722849d9d5c7bb7c149c48c2f782b35657
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:862da2865b990060330346d3e11b41722849d9d5c7bb7c149c48c2f782b35657
  - name: IMAGE_ADDONS_KN
    value: registry.redhat.io/openshift-serverless-1/kn-client-kn-rhel8@sha256:d21cc7e094aa46ba7f6ea717a3d7927da489024a46a6c1224c0b3c5834dcb7a6
  - name: IMAGE_ADDONS_PARAM_KN_IMAGE
    value: registry.redhat.io/openshift-serverless-1/kn-client-kn-rhel8@sha256:d21cc7e094aa46ba7f6ea717a3d7927da489024a46a6c1224c0b3c5834dcb7a6
  - name: IMAGE_ADDONS_SKOPEO_RESULTS
    value: registry.redhat.io/rhel9/skopeo@sha256:993f799d58c48151ecae7a84e63860f6c0039e8e18efed5ad67e7752f4b7e408
  - name: IMAGE_ADDONS_SKOPEO_COPY
    value: registry.redhat.io/rhel9/skopeo@sha256:993f799d58c48151ecae7a84e63860f6c0039e8e18efed5ad67e7752f4b7e408
  - name: IMAGE_ADDONS_BUILD
    value: registry.redhat.io/rhel9/buildah@sha256:a6e04c061b8d261dba85d01dcb64d3f7dba8c0b9765e03f05ec79850a248d75a
  - name: IMAGE_ADDONS_S2I_BUILD
    value: registry.redhat.io/rhel9/buildah@sha256:a6e04c061b8d261dba85d01dcb64d3f7dba8c0b9765e03f05ec79850a248d75a
  - name: IMAGE_ADDONS_PARAM_BUILDER_IMAGE
    value: registry.redhat.io/rhel9/buildah@sha256:a6e04c061b8d261dba85d01dcb64d3f7dba8c0b9765e03f05ec79850a248d75a
  - name: IMAGE_ADDONS_S2I_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:3696cf724ce7865626ae408d82fd87727c741e4d3eb3475c271ec6d56f0882a4
  - name: IMAGE_ADDONS_GEN_ENV_FILE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:3696cf724ce7865626ae408d82fd87727c741e4d3eb3475c271ec6d56f0882a4
  - name: IMAGE_ADDONS_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:3696cf724ce7865626ae408d82fd87727c741e4d3eb3475c271ec6d56f0882a4        
  - name: IMAGE_ADDONS_LOAD_SCRIPTS
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_MAVEN_GENERATE
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_PREPARE
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_MVN_SETTINGS
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_MAVEN_GOALS
    value: registry.redhat.io/ubi9/openjdk-17@sha256:cdbd64ba1b7826d09bc180fa19aa6fbc09ddb5bff5e02b7e1351353bbabebb78
  - name: IMAGE_ADDONS_PARAM_MAVEN_IMAGE
    value: registry.redhat.io/ubi9/openjdk-17@sha256:cdbd64ba1b7826d09bc180fa19aa6fbc09ddb5bff5e02b7e1351353bbabebb78
  - name: IMAGE_HUB_TEKTON_HUB_DB
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/console-plugin-rhel9@sha256:d37c28b1aaae82e81d26032658aefcf916c3cbbbd1207dec17e7dac176114b10
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-bundle-rhel9@sha256:a3a1bf93e16236fd79a6b1ac4b2599bb5d06e237cc793d48238f6a95a210ed72
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:862da2865b990060330346d3e11b41722849d9d5c7bb7c149c48c2f782b35657
