versions:
  current: 5.0.5-601
  previous: 5.0.5-600
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-controller-rhel9@sha256:1247e4111f8ef404798a4a62dd4d596635fcd8a6fbc12bdace2a808ec67d9911
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-webhook-rhel9@sha256:430f6cc162e7fca7f3dd26b5707dbe3c9a06a59068ea61ca38e86857b77d8af8
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-resolvers-rhel9@sha256:45ed4eb94add2e61909b4877b87f99ead93269825c2b4aa1e58f7291e326e15c
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-events-rhel9@sha256:a90eaf9527d8e0d178991e55e0eaf406db0c08f57e9dbe9d301c729508c59c09
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:b6d9cae8c3263ccf724302d5a55769dddf2a3ec8c4e6b42c408f667982f13118
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-workingdirinit-rhel9@sha256:c5cfca15b3ff1f48e8e8e71f655abc323c495c2188ca15096bcb490dc8b61b7f
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-nop-rhel9@sha256:124185b3013cc528d94bdcd7c9afc799df0dae0e4a87e96d5ef7b10c65abdea0
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:b6d9cae8c3263ccf724302d5a55769dddf2a3ec8c4e6b42c408f667982f13118
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-sidecarlogresults-rhel9@sha256:72b8440043697c16d8eddc4b28e389ef6eecf24270a6b9e85f8c4005080e20e7
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-controller-rhel9@sha256:0a9198a159be295785f8b3b9d38973c0d6d32a6f53530c5321c0f2866325aa58
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-webhook-rhel9@sha256:a06a3041bea1ab000d9ac26d85f8bad6d536ccfcc739efa86bb7c485c496f7ab
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-core-interceptors-rhel9@sha256:1b4d8cd8519508dab88cdfa2815fe54cbac27918bbc69fe94d0b1a16f434d9d0
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-eventlistenersink-rhel9@sha256:8941ddf8e8129f85ef22a7173d1d40e6488ac664cb79bf252c1c1dffa6c86b7b
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/chains-controller-rhel9@sha256:37e7344ed89766e82574f27073ad7a155ad798603cbd378fefb82378a4ee330e
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-db-migration-rhel9@sha256:6ba4e068f2ad6fde49bdca89b63faad1fa60766f50468b08aa14d391d906c6c5
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-api-rhel9@sha256:7af5276970a1dfa9699b953393dba851892877352a6b9ce47ed85a44c78dbc09
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-ui-rhel9@sha256:48f3e03942332b0389d4adb8b765c3b302d5a1efd6f062e31babb464d869d351
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-watcher-rhel9@sha256:db63931ba8fb4e217a152772f8bd6e83f7c1121e74fea0fe4508dbcd87888b0a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-api-rhel9@sha256:ac004e86d181642b268deba990f2c2232ac577c138a570747ed16ed13fe94b9c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-retention-policy-agent-rhel9@sha256:84bf80273fb3ce06a9882014ece9d21be4f06209bf395289b2ac12cab7d5fd04
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-webhook-rhel9@sha256:c775992841aa848bad80d37422bfaa2d8b54811c397c32051b4c533ffae06767
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-controller-rhel9@sha256:dd77a96b74c616b0997f6e032eefd5fcca46ac4d841c02b459e062ad2f910fda
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-controller-rhel9@sha256:5e00adbffc9afbf7d87baaca1e87b52f5369a90fd1509996bab11395ca5a87d8
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-webhook-rhel9@sha256:ca6285148d6a6ece681b5583cf4724da98228f97d73cc27e90464425b41ff986
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-watcher-rhel9@sha256:5bdbc16185dc0def4f9bb1d1b67f5bd83363f8c4285d91597641099322d2a030
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-cli-rhel9@sha256:311f490dd5aae9c66390d32ec9e897d2fad2fd8c98e38daee8232052585fe134
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:5e3519b24667b91986303285c6ad96cef5ca4e39663102356db62156eb86561b
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:5e3519b24667b91986303285c6ad96cef5ca4e39663102356db62156eb86561b
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-proxy-rhel9@sha256:61af2c1dfdfc42413bccfd948b858bee08b585425675b3494240125a69c0c49a
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-webhook-rhel9@sha256:4b4ea791e0e79a32fcfec7d15cd0ecbdd711600cd9104a97c2b00c3de76c2867
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:9af0f630c965e0af202215faa4e649cdd2be5613d916a84ff2f97aae8f30380e
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:9af0f630c965e0af202215faa4e649cdd2be5613d916a84ff2f97aae8f30380e
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/console-plugin-rhel9@sha256:f4062cbd71a67388e0f420b11c6369b52091be3ff64fbaa48889cf6c13dcb533
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-bundle-rhel9@sha256:2cf0bd289593e25b75cae6459b6d483bcca81716ffe22cc9428985e440ad89c6
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/opc-rhel9@sha256:7cf1c7f6f6541bea0a9e0f0271a9189e7f16f9ed9ffcb00bdaffafd73e807c60
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pruner-controller-rhel9@sha256:6044a42fc64ab4c299a3cce2260f51c59dc0e8834d8de64c160bb4987fb42220
