versions:
  current: 1.15.3
  previous: 1.15.2
  previous_range: 1.14.0
  channel: pipelines-1.15
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-controller-rhel8@sha256:37a2e37f3b088fec0f0bf22a5e225a761da49c7ce19f713679526e13596db8d4
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-webhook-rhel8@sha256:e7438597f9535e0f4320e0955f54fd424166ddb0e76c1f47ef36883bdf456055
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-resolvers-rhel8@sha256:81c057907ea153a41343bf04fd8a4e5a5429f339a25df3b933befb26cd6a8c24
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-events-rhel8@sha256:12484a8b9ba6db8a75fc6f1a5bf3df82344f7bdfb02ac724215a0088b27c213d
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:ff4958ab2328f67bb660a04dbb867f9b2f0b1195b2882e4082f7db12174254e5
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-workingdirinit-rhel8@sha256:85461fbb41e4a1555ce40caae7e1decf2a42cac6e4144a4361d84c98fa9273ed
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-nop-rhel8@sha256:807f5b41f43a708a1ccc65a148094537e2b03da42c5a3b9e2244ce2efe44c04e
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:ff4958ab2328f67bb660a04dbb867f9b2f0b1195b2882e4082f7db12174254e5
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-sidecarlogresults-rhel8@sha256:fb5aeb8fa5fa1ed59f51214b890a1736a30ac35a807f60bb61c94882148ca693
  # tektoncd-triggerspipelines
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-controller-rhel8@sha256:2f44e6dd9635844d11ca22c66996efe49a0e686e6fd5aa41a298b542b7546372
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-webhook-rhel8@sha256:1e97d1e40c8c79028bb68a4002f7de8d88374aee603d14386f4034c02227c1d7
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-core-interceptors-rhel8@sha256:cb582cb1a722a1648b2df47fe06f5d315d6b86ef06c8f2aae9f226da9e1ff27b
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-eventlistenersink-rhel8@sha256:85cb49d567eb71a85af7f4bce45c8f8492470171b70cd5ff7ad627b76fd13d22
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/chains-controller-rhel8@sha256:346edaa1fd2eeacf1991d2cb80809275cd80c3e5b997d2a89df4ec50def8e082
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-db-migration-rhel8@sha256:20e79eac7279c8a445824c5204e3e22c012eddc3eb0a16b25948e8806d737065
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-api-rhel8@sha256:7c364b92fa630e5d12977f6ad90d445534c8749cadbf28ff94e5eca8bc4db889
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-ui-rhel8@sha256:f944aef398b8a118705ec9e671a65862beece29ea22a1d2abf5d07b18c0bad57
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-watcher-rhel8@sha256:ae3c124069bfe8a44ee5609f81e636ffef47f8446532813c66abe5112c17798c
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-api-rhel8@sha256:2c667a2be42fbded28b4895948f009264c8098b17af09625a12b7f00d858cd46
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:f857003388583a95a2e524aad4c7fe3347a0d9f99d631dbbf8cb79431d2cdbef
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:f857003388583a95a2e524aad4c7fe3347a0d9f99d631dbbf8cb79431d2cdbef
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:f857003388583a95a2e524aad4c7fe3347a0d9f99d631dbbf8cb79431d2cdbef
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.stage.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:fe61698c401a300ceb65a930d218ca6c637bcc12da7daacb4307c904b16ff0cd
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-webhook-rhel8@sha256:0bb08a60a462c079a4219dca20ec1ee0938b074fb776f3bbf52f286f8a7a4c5a
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-controller-rhel8@sha256:e93d99c740120a30b229999b27dcef282c8f52afb3d82ec0e8fbf79a8524f3a5
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-controller-rhel8@sha256:1705e8a6b8ac4a2096cd16e7091584da8d289df7556f23ee8a8282f7ae6745ad
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-webhook-rhel8@sha256:7194085a3e884e37a72fec3d8c10a8116b857e16f667521904fa06dff3944736
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-watcher-rhel8@sha256:99ec7a5d98ddb35569fbfe173a3d5c157610601e8096e2fc52c475642e2190e6
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-cli-rhel8@sha256:3c15ab7947d4eff25126f74e9a3d197c9e19cf2572476117cfb1639e827f8f41
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:f510641a73fa736547469276db6c097728113a531e9d5d0ed3afb65434705333
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:f510641a73fa736547469276db6c097728113a531e9d5d0ed3afb65434705333
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-proxy-rhel8@sha256:bba38fcb8b18b8a702caa9836ffe5043ed52dcc721455e17c72c7ed49c90902f
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-webhook-rhel8@sha256:e3852b522c594de54c53f00c859ca50621c14792e788fa881da93b73a71ee131
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c99c0c49b657470f950c055382e1128ba12dc666225f62644e71903e9cfd1cb9
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c99c0c49b657470f950c055382e1128ba12dc666225f62644e71903e9cfd1cb9
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c99c0c49b657470f950c055382e1128ba12dc666225f62644e71903e9cfd1cb9
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c99c0c49b657470f950c055382e1128ba12dc666225f62644e71903e9cfd1cb9
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c99c0c49b657470f950c055382e1128ba12dc666225f62644e71903e9cfd1cb9
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c99c0c49b657470f950c055382e1128ba12dc666225f62644e71903e9cfd1cb9
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/console-plugin-rhel8@sha256:70d77f9da80ed07260a90c24bf4f3fcb4cd87e41f622c221a6351ef608a472eb
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-bundle-rhel8@sha256:6500cae42b8c3677239c37a41f177bfa342eebb080832a1194bd974638273462
