versions:
  current: 5.0.5-595
  previous: 5.0.5-594
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-controller-rhel9@sha256:a2ff2d65e920776e35d9dc9cdaf7777dbaca67518f05f2b958796db6c5f7dcc3
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-webhook-rhel9@sha256:b29f42b1f08b7550f8f0b0b25f1514784069f6149ccc34da544b46d60385c111
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-resolvers-rhel9@sha256:2f8c76a2f2fb8ecd55e41aade368b266a071945a0860e4cc577db9226c40069a
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-events-rhel9@sha256:6600078fbd21c7f298245b4f9b11a38f37a3a298cfce677f15b6e0ff9eb74767
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:f41fc49f819dcd37da6f9b69f2f7ce8ec04ff1545aa2d9f359e4cade4c1d9b7e
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-workingdirinit-rhel9@sha256:00c7aad3e8dab73af241d6ae2b3c26467a5c6832fe14bbff04a2d11cfc76a153
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-nop-rhel9@sha256:b7598a107bf71af12ad4b56d0ef609ad63aec74f0bea02896dc289fb5f726514
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:f41fc49f819dcd37da6f9b69f2f7ce8ec04ff1545aa2d9f359e4cade4c1d9b7e
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-sidecarlogresults-rhel9@sha256:4882fdd8de2ef84e17919728cadeb32d41b29345540862ea7258a602bf48cdbd
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-controller-rhel9@sha256:0a9198a159be295785f8b3b9d38973c0d6d32a6f53530c5321c0f2866325aa58
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-webhook-rhel9@sha256:a06a3041bea1ab000d9ac26d85f8bad6d536ccfcc739efa86bb7c485c496f7ab
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-core-interceptors-rhel9@sha256:1b4d8cd8519508dab88cdfa2815fe54cbac27918bbc69fe94d0b1a16f434d9d0
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-eventlistenersink-rhel9@sha256:8941ddf8e8129f85ef22a7173d1d40e6488ac664cb79bf252c1c1dffa6c86b7b
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/chains-controller-rhel9@sha256:37e7344ed89766e82574f27073ad7a155ad798603cbd378fefb82378a4ee330e
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-db-migration-rhel9@sha256:6ba4e068f2ad6fde49bdca89b63faad1fa60766f50468b08aa14d391d906c6c5
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-api-rhel9@sha256:7af5276970a1dfa9699b953393dba851892877352a6b9ce47ed85a44c78dbc09
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-ui-rhel9@sha256:48f3e03942332b0389d4adb8b765c3b302d5a1efd6f062e31babb464d869d351
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-watcher-rhel9@sha256:db63931ba8fb4e217a152772f8bd6e83f7c1121e74fea0fe4508dbcd87888b0a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-api-rhel9@sha256:ac004e86d181642b268deba990f2c2232ac577c138a570747ed16ed13fe94b9c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-retention-policy-agent-rhel9@sha256:84bf80273fb3ce06a9882014ece9d21be4f06209bf395289b2ac12cab7d5fd04
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-webhook-rhel9@sha256:8673789791142c8ec8374e8a656b1544967154109e7c9bf1144dea5b4310c426
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-controller-rhel9@sha256:3fedd85dfc3f60cef0637817e3174fd8f98c5408be9bd4ba92b36ce5c03fffb4
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-controller-rhel9@sha256:39d0817b221048b29ca98022443d322a1361e575dfe304bc7a0a70d29f7cf08a
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-webhook-rhel9@sha256:7f50da791ca0068e3e2046e5d563b2a1c1342ba7f32b23c4e310b74f59d16450
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-watcher-rhel9@sha256:03a08a0a0fba485b310ca0b297aa2194da3b82015fe9310fd8a70638f642b79b
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-cli-rhel9@sha256:9fc92eec2ff9f0882d5b7f22cd8fe5c98497719943fc7ffe96a934dd43c03bc6
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:7e1a6d6a5d4d4f498383cf1d9b05488968e9ca3411bdb52f3054bdef8a187ea6
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:7e1a6d6a5d4d4f498383cf1d9b05488968e9ca3411bdb52f3054bdef8a187ea6
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-proxy-rhel9@sha256:55c27e8a2f55d751b927b03f090c4d1897b0ba608c87a3f18f7a41a5e290ef83
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-webhook-rhel9@sha256:5e76b7c30e08be9853fdda621d334e4d41f3761be686c4300c62d719ac50bf74
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:9af0f630c965e0af202215faa4e649cdd2be5613d916a84ff2f97aae8f30380e
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:9af0f630c965e0af202215faa4e649cdd2be5613d916a84ff2f97aae8f30380e
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:99ae4804326d012f6432996f4c28d3d5ea367e7f219f4ba450070c5f3c4ca38b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/console-plugin-rhel9@sha256:4bec53cb6db4e6b5eb1668af71e32ffc22d83837435e8d80011c212f59f6a543
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-bundle-rhel9@sha256:17a243ea3155aaf00d5b91ff561a9353f9f27c6531fa4536d3932e17479fc21c
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/opc-rhel9@sha256:8befdc7866ba645c00133d7aef46ba782772d529af28a18604ea97e0cd4d6e94
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pruner-controller-rhel9@sha256:79ecfc957df41ef47cdfe0cef1acbc997522b9f0ff17b873f758e71486aa423b
