versions:
  current: 1.14.6
  previous: 1.14.5
  previous_range: 1.13.0
  channel: pipelines-1.14
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-controller-rhel8@sha256:6ff741f6cb2e1b62baee2410a2ce229b923d657fd0b9aa27b4716a9f9688aab9
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-webhook-rhel8@sha256:5871e6e4149d8485bf93cf9d90784ed5a5a1a6017a891057b97d7f55cf467545
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-resolvers-rhel8@sha256:23d236d9282b267c08ee3695fa34135a053ff9fdef1250d2a1fb2d26f2c991a2
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-events-rhel8@sha256:70911a93a26ef61e538a1a85a96953df6e872e05f4009b444bab1a7feb56f5d4
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-entrypoint-rhel8@sha256:b55e1ebe6e9f98b81ed815075859af56ccf79aa3ba860f7da397c70f44924909
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-workingdirinit-rhel8@sha256:621c9ad5a9bac8bb9ccbad652392d9c07de420613db437a5a2f296f67575700d
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-nop-rhel8@sha256:fa6686f8fb8e5e9c519aebc095be5f10826e86f31905bb6df3a8871690e8c02e
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-entrypoint-rhel8@sha256:b55e1ebe6e9f98b81ed815075859af56ccf79aa3ba860f7da397c70f44924909
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-sidecarlogresults-rhel8@sha256:78f65883625e403bb577a9998e279efce4a444f237d60ccd846f3c8881a3addc
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-controller-rhel8@sha256:fc083dfa1cd3070ba9c0a40cb5f7b5f1a6b79c1456ad99e40b89e2f779e18619
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-webhook-rhel8@sha256:c7fb922b5712a0a109791dde81d54215079de9d8baeb30ced81ca6fde4d0f3ce
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-core-interceptors-rhel8@sha256:eaabc4d041b3155e394ce0d93edc9992d58829ff96e9cc7b9641f38d9e5a0a47
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-eventlistenersink-rhel8@sha256:a76ed00097acbe99f117734bfffeec30d51f942243f01d8ee507efcf778669de
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/chains-controller-rhel8@sha256:44ad096c072e7f11c3705b0ec0bae30c69227c244964ec1c26f161756ad111f7
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-db-migration-rhel8@sha256:ab81e1a6803dae7558d88b4ef1e81c3f2921c3bbd9553584e62ee0e9154104ef
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-api-rhel8@sha256:6e46d20a50143767f33ed880647f60cf2800aac1d360fe01ba92c8fafce4bfb8
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-ui-rhel8@sha256:db6190995092e4c22f2541aebaedc76e049c04d4a383a65d70cb8e79bde56e60
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-watcher-rhel8@sha256:ff8d4e0ad08353372c43b2b7bfd01dce621ea81e8a4f0b834ec53b5ed9476ad9
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-api-rhel8@sha256:14ce5e0865b8ac15070c2c63eabd29d11959fc64af16a0490f6afb915a77de37
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:22b854a1d4a4d54f535d57b81b8afdc24d839176f4892635004acf3b54572bb5
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:22b854a1d4a4d54f535d57b81b8afdc24d839176f4892635004acf3b54572bb5
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:22b854a1d4a4d54f535d57b81b8afdc24d839176f4892635004acf3b54572bb5
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/openshift-pipeline/serve-tkn-cli-rhel8@sha256:db3ff043410d1dd0621fef4483761727f7241d788b136e446fb861953350a2cb
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-controller-rhel8@sha256:795695717f31445f6f9dc23dbcdaf462b2f83faf25d58e7461fff1af0822833c
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-webhook-rhel8@sha256:3997df7ee99262b0870c6ccbefe920d9290475f8e2fca24df98c47c7d1a69bcb
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-watcher-rhel8@sha256:96677840ff7977f810662b18b61a2a5afa40846656fc075b3be4f23db3777539
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-cli-rhel8@sha256:aac58c0ce7ab85e2751d47d5f3204a1efb37f60811c853c7a28f6140f3ac6388
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-operator-rhel8@sha256:a41fadf79f99c77d0966ed544d5876dd08957c94cb55b2d36480d14f9ee9e512
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-operator-rhel8@sha256:a41fadf79f99c77d0966ed544d5876dd08957c94cb55b2d36480d14f9ee9e512
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-proxy-rhel8@sha256:5cd89da14b871d04358d60ee6efe6589847afb59970a37467ce004e7bf61d1f5
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-webhook-rhel8@sha256:16ced78ad1c2171f7586641bdb984c0850600bc6694d59465b6c311047f1d109
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:b71519d75d0c13862f73ac7c09a9478456d4d4e652bcb722786a9b708c1a433b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:b71519d75d0c13862f73ac7c09a9478456d4d4e652bcb722786a9b708c1a433b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:b71519d75d0c13862f73ac7c09a9478456d4d4e652bcb722786a9b708c1a433b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:b71519d75d0c13862f73ac7c09a9478456d4d4e652bcb722786a9b708c1a433b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:b71519d75d0c13862f73ac7c09a9478456d4d4e652bcb722786a9b708c1a433b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:b71519d75d0c13862f73ac7c09a9478456d4d4e652bcb722786a9b708c1a433b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/console-plugin-rhel8@sha256:6415e4fa3275ac4e751d7a0c51114f5e7b9d206e6bc58f5885e5f48c3f6213b2
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-bundle-rhel8@sha256:e91a8f5ffccc5af8185611fa07b41ae70e5ce03f1e91493fb3cc65e663c31c44
