versions:
  current: 5.0.5-594
  previous: 5.0.5-593
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-controller-rhel9@sha256:578caaaf8fbecc4bac47be48cc5141111c7a16628645d7c6e56d178420162527
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-webhook-rhel9@sha256:a4bd7b60c784b5b2dfa132e652f50c7f3f2e2989ecfb3a26e4de5629055e78ca
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-resolvers-rhel9@sha256:75b2987983b0caa1e318ddf89836388c29a614cc42c9b7923b60b9fc667f8d16
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-events-rhel9@sha256:28a4351179abd39afa766cbe653d24908861b8d59f3de5d206142a38cfed1b4e
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:b93e74d47693ce1e91daa64d536415b427b1042412e9750c6c908a3c5a53c392
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-workingdirinit-rhel9@sha256:be5e925579e7e3f7a6e95e892756deb5f00da49ccf5bc97a5cf498d96efa3603
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-nop-rhel9@sha256:ff252fa1d9e7f62ed8bfa8b2728eaccb2888195d3580f770071b92510826a7b0
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:b93e74d47693ce1e91daa64d536415b427b1042412e9750c6c908a3c5a53c392
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-sidecarlogresults-rhel9@sha256:9c8b898f8d3e7e6df739e7d10f4b68de95a7488b33fb4de7dda0ca4795934671
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-controller-rhel9@sha256:0a9198a159be295785f8b3b9d38973c0d6d32a6f53530c5321c0f2866325aa58
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-webhook-rhel9@sha256:a06a3041bea1ab000d9ac26d85f8bad6d536ccfcc739efa86bb7c485c496f7ab
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-core-interceptors-rhel9@sha256:1b4d8cd8519508dab88cdfa2815fe54cbac27918bbc69fe94d0b1a16f434d9d0
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-eventlistenersink-rhel9@sha256:8941ddf8e8129f85ef22a7173d1d40e6488ac664cb79bf252c1c1dffa6c86b7b
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/chains-controller-rhel9@sha256:37e7344ed89766e82574f27073ad7a155ad798603cbd378fefb82378a4ee330e
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-db-migration-rhel9@sha256:6ba4e068f2ad6fde49bdca89b63faad1fa60766f50468b08aa14d391d906c6c5
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-api-rhel9@sha256:7af5276970a1dfa9699b953393dba851892877352a6b9ce47ed85a44c78dbc09
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-ui-rhel9@sha256:48f3e03942332b0389d4adb8b765c3b302d5a1efd6f062e31babb464d869d351
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-watcher-rhel9@sha256:db63931ba8fb4e217a152772f8bd6e83f7c1121e74fea0fe4508dbcd87888b0a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-api-rhel9@sha256:ac004e86d181642b268deba990f2c2232ac577c138a570747ed16ed13fe94b9c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-retention-policy-agent-rhel9@sha256:84bf80273fb3ce06a9882014ece9d21be4f06209bf395289b2ac12cab7d5fd04
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:2d7333d356b087734b40be5bb3952fe71b2f3236e396908a1b523fa8c51b72c8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-webhook-rhel9@sha256:35beabf371d3167a0585473927bc809c1734d9e452aea075e38952554028cc07
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-controller-rhel9@sha256:3fedd85dfc3f60cef0637817e3174fd8f98c5408be9bd4ba92b36ce5c03fffb4
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-controller-rhel9@sha256:3ff0097701fc6e1de5edda5f7c0066249273bcd705aec77d7c5dfa521648b89f
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-webhook-rhel9@sha256:82481553caebddde61c6c1adb61306f17fd104cd126a02f095704b563c55c5d1
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-watcher-rhel9@sha256:66f8c53b9c4d6afc2af8d4ea84e530b5339a9f17bb9266bec4e48ed576fc0598
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-cli-rhel9@sha256:d8c565bfea2edc4f6b3af935b38635d679d8c9ca5127823a9e14081f4ede150c
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-proxy-rhel9@sha256:977fd2d48245db7285e4e65e8944d1c127975bb4446c62934bd34e3f3d62618d
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-webhook-rhel9@sha256:adc010c520645982b711031d300c3905291a3c3ab5344fd54397832ace672ded
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:8befdc7866ba645c00133d7aef46ba782772d529af28a18604ea97e0cd4d6e94
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:8befdc7866ba645c00133d7aef46ba782772d529af28a18604ea97e0cd4d6e94
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/console-plugin-rhel9@sha256:4bec53cb6db4e6b5eb1668af71e32ffc22d83837435e8d80011c212f59f6a543
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-bundle-rhel9@sha256:2715e6f59e3e0e9a17e50d9cbd4b2e791d5e3ab2543bb0567d2924278c8fe435
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/opc-rhel9@sha256:8befdc7866ba645c00133d7aef46ba782772d529af28a18604ea97e0cd4d6e94
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pruner-controller-rhel9@sha256:b773f7bf7f13cd7ffa2da6282509400326598d8a5d382a0c81b417e14334a16c
