versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:0d0e2ad50b21cc1d336c725081c11cde1a2df602e1b171b6310750bbec92d4e2
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:356cf385f36a8cd222ae4c3a583b020c456f059e71c3b7be795810f5d7fe3a94
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:b71f2cb9f0457aed196b95085e500b2c268db043b2cccb3175c5a43a832d451f
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:878ba1a2bdef8dcc3e5496ba955ec4821262fcdf8c09856e0143791916516bbf
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:e8fdd9207e0f546497a69bf88962cb593ad6c4df3f35e0e22376e1e579f60f52
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:ac1d8775d67db1b7efd666ab07ab65bd693f3d949371d929c1488ff1cd7297e0
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:547629f2f8e7bf819927de18842508a27f3b190a827eb4849253ddaf6849e910
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:e8fdd9207e0f546497a69bf88962cb593ad6c4df3f35e0e22376e1e579f60f52
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:9af73959324db483967b2deba47d1a1b2c17ab476b224af74f7fe7cf1212e491
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:a8c4dcbf338ce195f6487bd534fe8a32ed14ed50826381af9f7b78e39e399d85
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:f76ce397cb2005b7700d747c706129dd07eb64a953fb082f57052745d96dc2b9
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:5be559c545f6dd0eda6e51a509e875fcf8779f445abb25cd043e5120991cc731
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:4a7529a7f91dbc85b77d0a1b9bdf1cd2d0b4ace9b137d7f7cc199c21dba4bc88
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:755636464f76eea41ccd79c24a679a05391bc4e58662112e4d6c2d904ea9a5ca
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:cab1c265f9a83f16101dd8b866d5bafac58efed43fed3c631587d63e2e90668c
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:92aec9145c3b6489dba92dbc1452d7357f084e8292e2ceea76c31db87022ec92
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:f0152a56754acc93f64448878cae4f0240b32c857f9b2a37f02a20bf51c2f07f
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:623246f8d6c4c402b83c156170a0b89d5f1383c3d971a4f047ebb76103192932
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:7d63862c1bce8120d0a8db34194d4195e534f226dd105975c72fe887340a2e00
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:b8d7dc1aa44ba096bad8254f8e30a910a2a9898b09b5ac1be51a229350cc0b5b
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ec3a3b5ec38852a018a9de81305815630ac83d7b7052324cb325039dd5143821
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ec3a3b5ec38852a018a9de81305815630ac83d7b7052324cb325039dd5143821
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ec3a3b5ec38852a018a9de81305815630ac83d7b7052324cb325039dd5143821
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:9c387415e9268a0c4887dfb356d07a4156395d62331019bdc19469e33048d346
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:0a1d10debf281342b52fb500d59eb6659df1ecfcf34139636a4c85c70650a7cd
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:0738c6f2b35372cba11c3d39d6126757baa7818cee5b0aa5edc5c16a7c745faf
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:e1249b9e36bbcf3e7125ddac388f35db37226e4b7dbc67f9152278c95bf60ae0
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:21db738e30cb30dc8a071e9fd8f39b8f946656bbbf6d27ccad40ba60cec31df4
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:c81860fa804a9df62feeaabb40eeacaf367910ce78dc64d5605f33f7a90fb158
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:c96244de030ef4506e306d4998a5ff24203cc3604d340ee49725d1e32bba87f1
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:c96244de030ef4506e306d4998a5ff24203cc3604d340ee49725d1e32bba87f1
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:767e32b3e403350af21004faf2b624f6b5be60759f48aef679d64adfe043e736
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:72f0a5782b42d0cb1414cc3a3fdeaa051dfd06d4045905a4b8e38902c634d0ed
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:c71c1dca4fa3d71abdbd0ce2a02e37cedf4f885b274c3834f183379106fc96c5
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:c71c1dca4fa3d71abdbd0ce2a02e37cedf4f885b274c3834f183379106fc96c5
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:8a7a419d41837fec32726f0d94f893609d60a3915bcfb628b3e9211193d98e1e
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:f001b5c39875c0822405b5576a7ba5b1318b440c4c8911dbfc001fcfb19aad72
  # opc
  #- name: IMAGE_ADDONS_OPC
  #  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:acd78a6c31f905814325f9f9f4da5e5a78f63d0a3b36d84edbad217e85265608
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:8b3074066f9209a9187cc76a171d033d2ff910278b519ef973730b637c10f387
