versions:
  current: 1.20.0
  previous: 1.19.2
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.19 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:9272518f49eb5f85f4805fa54fd2de3cff0fe626e8656ec8a2d8c566060b4ae9
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:79f970374550921043fb5d5dd33cd0bce78336ba34632409bd4fec1e43eeaa1e
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:07a7d4682e73ec9003707e061054875c28f64d0631829d4f3319aaef6ff56b71
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:7220067d27368ecb3f9202b0cb94ed38870c09764b9d18807700aaad8d3287e0
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:49044e8b68dc775c33d18095b7e0c29f00e6db8444cd1c836b7db6a901c3fe96
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:8260f3188193e9971e8e4c06cede56c1238e4c8cec0cb12d67dc1fc1e72fbaf0
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:c4d05e546c466c57379fff502816012f615be073eb8cdce54677b4ab206a3f5c
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:49044e8b68dc775c33d18095b7e0c29f00e6db8444cd1c836b7db6a901c3fe96
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:a5db11462f4f54ff648a4d822f267f8fc4d61cf6d1c658324e890916a8ebb529
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:8a15d7cd8cc3f9f2bf83f0c86d82c6d57958e71e08a99b59bacbf777622553ce
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:bddfa088562d62b919e3b8e37e84b77cefc08ddc641d8b9c7f87d083a04b591f
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:cf91889556d73478827aec81ae13827132b62a2ff162f0f17be01ad34334b916
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:65cf457bb5dc97fd936aa1d132d7e4891c5a0ca1956205325ba513c855818f89
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:1af717631248c10233b1a5b69e177578bf366418b5a2da1c100578bad7f99670
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:264bfa6806abc59cfd91cdf7e78e82999f47032621988d3bbe9cc8368be1575d
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:352cf8b5d2d74304a7ff30cb8eccd3df0168054317fdce37291437fa70a27177
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:09ba9d7ff463cef8fc6a0ba46867d343084130feaed51d3439e9046744ec1cd3
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:5a4f5ab551e6e37511ff9f18381850a6a823ae7c477cd9311d7c7871d83fe52c
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:f1dd08483dddace45153fcae3c2b2184198287c129f9ffa0e128d5e425c62fbf
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:7a7ca798366da4d565f7e836f2556d2297b0b404410d32455faf8242bdaf9d98
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:696f630b339f24d33ad383ceb614cda53f87eda37afcb653e71a26f4c8958f4f
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:696f630b339f24d33ad383ceb614cda53f87eda37afcb653e71a26f4c8958f4f
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:696f630b339f24d33ad383ceb614cda53f87eda37afcb653e71a26f4c8958f4f
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/serve-tkn-cli-rhel9@sha256:bfab1c56f1362e4533143634ad043c8cfd390d08b72d0740ef2518e12cdccd43
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:b708e0ed966fae1c851c3b96e0ae4b79a041969fd54eea6f6e5cc1b05c30743c
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:f6115cc37d739aa5d830182fc422700c0555a9bc995ca2c4f53cc0c6c5b1081c
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:9b0ca961aa60329d3963a79a986e5a4440c27459aca90ba6ca804556a95398ab
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:9799b4acc677e88a892e35d370e98f7f8c973f37aa1b6cb9a5b5f3117b855129
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:f0a6616e9a5e188bbcce8531f067a08a764dd3f56e1c3f747788248542671a73
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:689cec4b17db2c5da23e28889c09a1e165202b10e0412283e648ff99f7bae185
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:27a10e2986bc7c7f94be3be212493f54030b79047249b699ea2755aa7ec37c17
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:27a10e2986bc7c7f94be3be212493f54030b79047249b699ea2755aa7ec37c17
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:df5dc8fc82649aa77c16acf7e0075498b9f44cca99e3fc9b73eb67d05133884c
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:6e25a47a9a5ceb9ebb82bae5016dfe31d1b46ebf1ea253726c8d0f84c6d2636d
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:3ec2a9687b8b957e00d6afa09a57bed088734f6fb50cdf8cb83779f436dc2269
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:3ec2a9687b8b957e00d6afa09a57bed088734f6fb50cdf8cb83779f436dc2269
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:78e488c2849e6d8cadbbd627e072355be5a361cd37008482240f4bd507eafeba
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:78e488c2849e6d8cadbbd627e072355be5a361cd37008482240f4bd507eafeba
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:78e488c2849e6d8cadbbd627e072355be5a361cd37008482240f4bd507eafeba
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:78e488c2849e6d8cadbbd627e072355be5a361cd37008482240f4bd507eafeba
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:78e488c2849e6d8cadbbd627e072355be5a361cd37008482240f4bd507eafeba
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:78e488c2849e6d8cadbbd627e072355be5a361cd37008482240f4bd507eafeba
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:ff66b65a70f6b5f83556514fc70939a3895c4636938205a6ec7dfbb82856d1e1
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:d38516b0dcb53d40448f8d53dedd67e6477e7d32c1e2f066b4b131616322423e
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:9dd2b74d35ebe8ffd1e161024e6913dffcf9a597c95c25e9263fcd70a285e8d3
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:d733b452aa8185a0513573890e93e82474597401768b823eeca7c5d2be59d04a
