versions:
  current: 1.17.2
  previous: 1.17.1
  previous_range: 1.16.0
  channel: pipelines-1.17
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-controller-rhel8@sha256:db27cb4f0c350d99546b0f1bdf02d1ba271a8053a4552d88ff302adca60a3e29
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-webhook-rhel8@sha256:41e2f2c7397a8b9e093e18977666e93943734f51780c769c99958ae1d20af53e
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-resolvers-rhel8@sha256:4a96f1bb7e3a5c7ca62dff2199fa15ef964b129e4e36e9619837c1221538f496
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-events-rhel8@sha256:4b87782b35e7284a365c49f1c094aae98531ac630db1958294009c041a2d8440
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:e673c20fff2fc684f5098282dd6ac6cb265045945249e995b81289532ce8c856
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-workingdirinit-rhel8@sha256:9668d852123b160e49511242371edc6e941a8e8b8c2ffa60080d91cc6b97d3d7
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-nop-rhel8@sha256:4240501c076605a01d969328bbb8ad885c598b44ec1dc1c066312491a0eb6715
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:e673c20fff2fc684f5098282dd6ac6cb265045945249e995b81289532ce8c856
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-sidecarlogresults-rhel8@sha256:37b695300cb3e901fc10aa504a3ac9d476c0021b4954f33e5226d97009e2cfe6
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-controller-rhel8@sha256:650391ffd3e4c7b173bf9d718405b2375c6ff2027abc0b7ce4f67e79e7ef4b81
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-webhook-rhel8@sha256:922b9e86a674a6f3eb82f510569ab9cde97a1ad833c263335cd4164bf4164b66
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-core-interceptors-rhel8@sha256:7abc88bea01dd6513f6e48334f0b98501f909a1dc1ab9e83efeb3c1a834f8f92
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-eventlistenersink-rhel8@sha256:4224040b00cfd76e85f80aecc5095098564cc62e9c477fe2f7a428b30df7d4d9
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/chains-controller-rhel8@sha256:c92ebe828b6ced6c93a3df5f4ccdfba022471729ad08b184de2f7410ecf592cc
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-db-migration-rhel8@sha256:66309ae437c4647f48efe3d6f2b696df83859323700427d0025b94795751a859
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-api-rhel8@sha256:0b6ee6cd98cb7e835cfc9544996c6f85288d7252071c100bed853eb593d6befb
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-ui-rhel8@sha256:61c9e8b1660d8935ee316ecc113e8141daf05149d172685cabd861ae8aeed3eb
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-watcher-rhel8@sha256:26f7b695fc1430359ab2bfd2915cf0b7e88b06d8695e26761bdc2ce8935f0fb3
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-api-rhel8@sha256:d851a2dd8ec95bfd7ac6ec5515c8cdadfcbfc6e6ec84b40630b4fe595f978fa5
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-retention-policy-agent-rhel8@sha256:b5cceead6b8e9c99655c9ba810679b9d6fb978e5ff18d020a46d475c4c26fa29
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:429bc3d6044ca7dab780ff4b5eb91d42d38a29eb7ef428a25c53b7dda49871bf
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:429bc3d6044ca7dab780ff4b5eb91d42d38a29eb7ef428a25c53b7dda49871bf
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:429bc3d6044ca7dab780ff4b5eb91d42d38a29eb7ef428a25c53b7dda49871bf
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:41ec6db921812fd1e80b05d51c224ddbce63bf0c57f02ccf07461d2202e97b90
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-webhook-rhel8@sha256:a14270967460883f283ec1ce17ff8b82db1e0777dda4f6d690f15ac38dcbad85
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-controller-rhel8@sha256:84eed8ba1189448e02ffd284c7d913e7b3cb7efe7a8e5b0edf890f7eb17fc439
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-controller-rhel8@sha256:8e52b4b31b0d9ec772abe6e6ef9c6698e89893395f364968216bebc3367da4b2
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-webhook-rhel8@sha256:7c710882752f12be3c22bedc8d32096c111e42c5b9b392163f61cf8d72be3ec0
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-watcher-rhel8@sha256:a392d2c85baedd7428c579e91d9f8acf8232399b90523b1093dc3447aaf56a16
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-cli-rhel8@sha256:7e9fde0a904afe45e78e71435689dd12a6bd59856c79ddbecccbd4de1e237a01
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:eab798472b76bd51235198fd3b95189740f8d650ebc6bb01fe653c025c1defaa
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:eab798472b76bd51235198fd3b95189740f8d650ebc6bb01fe653c025c1defaa
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-proxy-rhel8@sha256:99f5383d8c6bc046a0bf48fd6c2064a5d055645085248327305f3ee4ae71979c
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-webhook-rhel8@sha256:df11cdbab2a1c6b9b800ef124c73f2fb5e3981402b21bc822ccc13e95836197a
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:4fabae1312c1aaf8a57bd2de63bd040956faa0c728453f2a4b4002705fba0f0c
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:4fabae1312c1aaf8a57bd2de63bd040956faa0c728453f2a4b4002705fba0f0c
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:4fabae1312c1aaf8a57bd2de63bd040956faa0c728453f2a4b4002705fba0f0c
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:4fabae1312c1aaf8a57bd2de63bd040956faa0c728453f2a4b4002705fba0f0c
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:4fabae1312c1aaf8a57bd2de63bd040956faa0c728453f2a4b4002705fba0f0c
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:4fabae1312c1aaf8a57bd2de63bd040956faa0c728453f2a4b4002705fba0f0c
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/console-plugin-rhel8@sha256:44da76d75f567c2ba623bae646e1d552d2c0fded1accdde3aab4f4bcdf3adc28
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-bundle-rhel8@sha256:60635156d6b4e54529195af3bdd07329dcbe6239757db86e536dbe561aa77247
