versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:fbb97c3301176e2ecedd48824efe5397bf2e962a9f24b3a35b465f7cc4a80674
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:8e19f06ca3bee8d925b4327f281da9e1dd6573b922d35de702931dff69f57f9c
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:cdf3f368f552a05f22f6eb6e1f561cc3b5d906de3cf15cb0fde47d5ae1655ba3
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:315c6983783ec2a32b3eeee020cd9a3c4c4584cb9f467d73dc5f8d3f1b085fb1
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:d7566bb3840c5e6097c8545cf1fa8fdf9d72fde2e3af5545041e1b55fd25b026
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:0c4ee1e6e679415e1323842ef0a3667c9942f21d3239b83b3aa3773624358015
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:c1c0cb5c202a1cdffbd6801b0dcfb9fd9f561fc9de38fdeed838bbe99c15256a
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:d7566bb3840c5e6097c8545cf1fa8fdf9d72fde2e3af5545041e1b55fd25b026
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:b057a89ed67448acb93ffd7734b197fe4cceeda1b2f3c6aa9dca4d9df3b1ad0d
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:2beb9440193c23b72b6ab244eaae6037d4b5ad52cda95e1eab4a84df8fd83f9c
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:fee46dd9a1945763cbd4f8a6d34c2b1794d60fce2736f2b16f3be83410bbb2d9
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:de1abbee622315eb7a233487cd9a9b92c8d15ced1edf914c0f403d769db76b7b
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:60f07652693ab3424f60c5326ba8099dc002c036ebc12812a263a3b3b7ae9f0a
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:cd5d383a159b6340a35249ee673445da22bc04f5cd3d7c7e7417fbf46ef5baf2
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:b03a4d6036d6b93f7c5a99b14e423741d530353bd2fe876c7c74def346b43eea
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:57a5ffc3e0072cb2c0d3dcd396ae72cbbc2352d1043e6492c0fd317bc02d0f5b
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:e29edce3cf4143f34d3c6c7996c06ce51398f589e2f5193d04bc50478415e927
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:c437a74e656d42453f634972022259a46ce492c6206ebb1f101865bd734f0e5a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:33ede9ac92a938a4b7336cd72ac3ff5dbc2226079f52275863fff5fc4535a06b
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:960ee683274e598ca38fe60ae7b5265e6404e4da3a9d9fb563b32a76664338e9
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ed42761507b4d623cff61a825be45f46b9cf73494df52b3b25351f9030d8631d
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ed42761507b4d623cff61a825be45f46b9cf73494df52b3b25351f9030d8631d
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ed42761507b4d623cff61a825be45f46b9cf73494df52b3b25351f9030d8631d
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/openshift-pipeline/serve-tkn-cli-rhel9@sha256:800d8d053e1e6f8335ebc70e3280a56717bc1186461125c00b2a5c5e6f2c52a2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:dcf81e5bf301a1c04a785b7deb8700a5b90a8cd45a1d216c53ada77c814e3f2c
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:285c8c20751b24695c5d4735cd656ac6c57cc29439103c96c628f34e9a6d6949
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:21fa465698b0d31fa987c2652aeb7cfebe87ebd21a7508b1b8ff1ff81583965e
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:91be0a5e021186a2bad5222bdb5880e7effabf42b7af75cde2803185246f4c9c
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:925e36dfa4d42beef29ea22140654128aefa2c8bab0ead312f2545285b0763cf
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:801cbea0b066c204082e800ab501e148435deb76a7090d45f5ec1dd549863b12
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:33ce54e6aef189963fec3c586208d34db6da2517aa8550951fed61260e11c775
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:33ce54e6aef189963fec3c586208d34db6da2517aa8550951fed61260e11c775
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:c44a8c4f4c045d0492384884495c6f3611272e7890bd35ba43cfe1932eeb270c
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:74f1057fca7b3f531ce02a1f89b405a838a0e521fcbf5d70f0af3a0b197fb4d4
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:5d1d893ecf24bb88114a0f5a31e53de62fda0272a0f0243484af138e86acafd9
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:5d1d893ecf24bb88114a0f5a31e53de62fda0272a0f0243484af138e86acafd9
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:ecb8bfb2161a0ffc2ccc2aa4f8f1082a21ac18e991812b0b5d32f8d84fb6a1c0
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:ecb8bfb2161a0ffc2ccc2aa4f8f1082a21ac18e991812b0b5d32f8d84fb6a1c0
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:ecb8bfb2161a0ffc2ccc2aa4f8f1082a21ac18e991812b0b5d32f8d84fb6a1c0
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:ecb8bfb2161a0ffc2ccc2aa4f8f1082a21ac18e991812b0b5d32f8d84fb6a1c0
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:ecb8bfb2161a0ffc2ccc2aa4f8f1082a21ac18e991812b0b5d32f8d84fb6a1c0
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:ecb8bfb2161a0ffc2ccc2aa4f8f1082a21ac18e991812b0b5d32f8d84fb6a1c0
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:5f2c3e129cbccb37e1f0d4c6218158681ef1cdeae818dcb44c923fb41a7fb948
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:6ce2fac2c1c3c9c8e0834f84aa0125cfebbd6a562e59effb493c2183d5f2d07c
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:11203b74adab95d2dd06115f0fbb9a722563eb43c770da092663207c79d28f54
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:4a11f128b5a037b8663ff3c30ff59d0dce5a1842ad593f8ca9caaddf9fc6419f
