versions:
  current: 5.0.5-479
  previous: 5.0.5-478
  previous_range: 1.16.0
  channel: pipelines-5.0
  openshift:
    latest: 4.17 # lastest GA'ed openshift
    min: 4.16    # Minimum version OSP supports
images:
# tektoncd-pipeline
- name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/controller@sha256:146252262d2d3d517053c7a551b57eb6bfa4cf492fc6f4a84b09a6bf4336ba88
- name: IMAGE_PIPELINES_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/webhook@sha256:6cefacbcc895812182612d28e32f10fb638e62daabeb6619c3a2b006bbbc7c27
- name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/resolvers@sha256:6a8d544661213dc7cd016543f62d77df114904d5c7b0e8df237260c0738ada4c
- name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/events@sha256:e5787893bc6571e15c32b0cb5ad519d53af145780583a6e753ed9a3ce5009176
- name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:431f336c959c7466cea1f35c2c547e927dfd46448bc1250e24c63b61e8a32189
- name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/workingdirinit@sha256:5e08a390e234f5f47469f0b73ff6c6ad81a8e73c4fbf1ec738cbdb0e204ff46c
- name: IMAGE_PIPELINES_ARG__NOP_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/nop@sha256:ff135dbcb68ab206811919b3a2f578ec460df2a710cb6027118fa34806a833eb
- name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:431f336c959c7466cea1f35c2c547e927dfd46448bc1250e24c63b61e8a32189
# tektoncd-triggers
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/controller@sha256:0cce0ab1db29ebe9187eaca02508eacfdbe6f9d83790f2a95f6a3a980f61b68f
- name: IMAGE_TRIGGERS_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/webhook@sha256:26251e47a78bbe2a454b61b307665a9dd57201ba065892ca08d4a5d31e1bd823
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/core-interceptors@sha256:e5059ad8a2ccfc5e276a79e19c12eb982730e3806e6a2bbb6334b4ff5efcaa48
- name: IMAGE_TRIGGERS_ARG__EL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/eventlistenersink@sha256:b8c5c5594f978be468be51c52ea3d81a33fa405c39e681bf47369f6ecb6e31e6
# tektoncd-chains
- name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-main/controller@sha256:a15e0cd710b54269a9ca5fa113fa91ebee3692d009a2c68767d80d9e61bc3754
# tektoncd-hub
- name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/db-migration@sha256:6a62a6eaf7de42fb6fadb17bc33d92e1f58e7642a0d4411cc84a2d196a4aa6b2
- name: IMAGE_HUB_TEKTON_HUB_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-api@sha256:748616fb0dca45a0a9bc38f7b0558da2c2ecd62ad4611ca9cdf9a4c3a14dd7d2
- name: IMAGE_HUB_TEKTON_HUB_UI
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-ui@sha256:8fdc88542c6b613bb09e2e709d99e94de76b09d5d511b965e5e268f4e7c430cc
# tektoncd-results
- name: IMAGE_RESULTS_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/watcher@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/api@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/retention-policy-agent@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_POSTGRES
  value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# tektoncd-cli
- name: IMAGE_JOB_PRUNER_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:40a0c14624a6d2df5c5d4725b3d6fa35486df8b0135b419f3d572f4a48c0e539
- name: IMAGE_ADDONS_PARAM_TKN_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:40a0c14624a6d2df5c5d4725b3d6fa35486df8b0135b419f3d572f4a48c0e539
- name: IMAGE_ADDONS_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:40a0c14624a6d2df5c5d4725b3d6fa35486df8b0135b419f3d572f4a48c0e539
- name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
  # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
# manual-approval-gate
- name: IMAGE_MAG_MANUAL_APPROVAL
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# pipelines-as-code
- name: IMAGE_PAC_PAC_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/watcher@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# operator
- name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:5173cffb590a20b2387bedfba0a24513954c06b9408257c3a2d9fb19b2e60e3d
- name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:5173cffb590a20b2387bedfba0a24513954c06b9408257c3a2d9fb19b2e60e3d
- name: IMAGE_PIPELINES_PROXY
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:70340390dc590b3510b3bc5e05732c7791c152360dd109afd093da3050cb285e
- name: TEKTON_OPERATOR_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:abac6ad1e7f07d82f8034385a38de48f684487bd64d227688a620604733d3bb2
# Addons
- name: IMAGE_PIPELINES_ARG__GIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_PARAM_GITINITIMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_RUN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_REPORT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_CLONE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_KN
  value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
- name: IMAGE_ADDONS_SKOPEO_RESULTS
  value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
- name: IMAGE_ADDONS_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_GENERATE
  value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
- name: IMAGE_ADDONS_LOAD_SCRIPTS
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GENERATE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_PREPARE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GOALS
  value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
