versions:
  current: 1.18.0
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-controller-rhel9@sha256:b95040d63b229183d7fe3f2e68ce9b4ae172aabff2d6d1563198c4455010118e
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-webhook-rhel9@sha256:db2968d9614ff2a4c13555a9e6f269ae5fb7cc9b0f38cd2c72e9c2b8dfa64377
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-resolvers-rhel9@sha256:a142f84994a9f99ba5db6c157901ccc47561495487c62143e035cd886a55bbbc
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-events-rhel9@sha256:f6cbc77c9443fad0fb937b9628916f4d630af228126817e4c303f57779d096bd
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:cc51bcbe217c896d28e04a5a1f1a028195294a708b93676c33216fd967b16574
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-workingdirinit-rhel9@sha256:2baa1b847d623530e59562f63558227241489e64d8fa4a9e9240c0658b3b0106
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-nop-rhel9@sha256:5c539f3ffe40f60a67548897899efde9ea28378e9ffb434fa60db44b8a6ba809
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:cc51bcbe217c896d28e04a5a1f1a028195294a708b93676c33216fd967b16574
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-sidecarlogresults-rhel9@sha256:51155166e96a39494622281fd23fde8dbb4e81058d7b21d72eb410ebc448dd2b
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-controller-rhel9@sha256:1eed9373fae7d06b5a05fae256711dbf287511024b00c919c585ffeef40cd143
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-webhook-rhel9@sha256:5fd993b84f9ce6b5958d5528a0528ee32d25533c369fafd90624acbfb08ea348
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-core-interceptors-rhel9@sha256:a033df10363cc56b8e01c234ad3170f55d925ea62bcb84de3daeee6036394a26
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-eventlistenersink-rhel9@sha256:8b068ead12ccb12db26ca23db7dcf7a9c6e43d807c82070d0abbf20bf12c6638
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/chains-controller-rhel9@sha256:91aa8d68355cf75aa655978b3fe4b4ff32191de5e543b9ec371111909c139689
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-db-migration-rhel9@sha256:d66d8317151276aa662e057aff66293e8eaa0978654b578f7345cc8a4610065d
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-api-rhel9@sha256:d3a28a26522bc95885473fb96f1970a3787095dc4d26d1811c782d64c508d159
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-ui-rhel9@sha256:4a04d5a43806fa684d31bd5b2c7091a1d177f6311bea6fd7dc3128bb1c2e6a0d
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-watcher-rhel9@sha256:c2edecd690b185de1a6d2d0c42282a3f13ff9e25ecd70692c6b1ec2dcaaab154
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-api-rhel9@sha256:8d313ab05eb06dd1ea0e2b2e0ab9936ec79a999521c6ebb52e3312c178fc262d
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-retention-policy-agent-rhel9@sha256:0aa16d5d245e11668e1cc2eaeccbe7dbb7f1022c95c592e086326725d5fd1121
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:77a641b55e60bbe09c07b0ad75bb0a95954fab66f689984a4b1607d3e93b84d1
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:77a641b55e60bbe09c07b0ad75bb0a95954fab66f689984a4b1607d3e93b84d1
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:77a641b55e60bbe09c07b0ad75bb0a95954fab66f689984a4b1607d3e93b84d1
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18yhbqwBheJN2EN BN SSCJD  DLH @sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-webhook-rhel9@sha256:47e979886e2d8337afce13320acaa2cfa11f9346893873824331b37d92c103f0
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-controller-rhel9@sha256:1cc793cc433dbc0a74037079c213d2fdde9dc424e533a282dd73c8119d135848
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-controller-rhel9@sha256:4c8cd02b16a16b86b4a2dbc8b4372890d9b3e41bfb16bb7de253f7cdc89305de
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-webhook-rhel9@sha256:fcc4b89adb791a60217b19c74ca55e30750eb78b607efcb5ebb4fd5929acd3b1
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-watcher-rhel9@sha256:90ee1e94d638a00956b113dbc5855eb5686f5863b013df81fb6a764b15bdf9d7
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-cli-rhel9@sha256:df99b2ce110c059435081309ec9da806422eaf0bed4d7ca9cdca474d121b2e1b
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:edf06a6260b122861843460f36a3c55f2dd0ca14cd49227e1ae672c9afec9226
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:edf06a6260b122861843460f36a3c55f2dd0ca14cd49227e1ae672c9afec9226
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-proxy-rhel9@sha256:057d7b124735f8b6569bf7866d0c5a5d3e31bb3ad4a0388d8e13e2bfffe705eb
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-webhook-rhel9@sha256:ffe85a9b5b8a8f03b5ddbf2e220531a715f0fa1d867b166166b7ef2aaadb7d0d
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:0ed4102e5fbeeff6bec80aab58f23836dcc7176b8280a4cfcc2c0ce52cb845a1
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:0ed4102e5fbeeff6bec80aab58f23836dcc7176b8280a4cfcc2c0ce52cb845a1
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:a7eb236e9d11438077327ea1d51d02447e1b3c9bcfb14a31452bbd84847a8062
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:a7eb236e9d11438077327ea1d51d02447e1b3c9bcfb14a31452bbd84847a8062
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:a7eb236e9d11438077327ea1d51d02447e1b3c9bcfb14a31452bbd84847a8062
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:a7eb236e9d11438077327ea1d51d02447e1b3c9bcfb14a31452bbd84847a8062
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:a7eb236e9d11438077327ea1d51d02447e1b3c9bcfb14a31452bbd84847a8062
  - name: IMAGE_ADDONS_KN
    value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
  - name: IMAGE_ADDONS_SKOPEO_RESULTS
    value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
  - name: IMAGE_ADDONS_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
  - name: IMAGE_ADDONS_LOAD_SCRIPTS
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GENERATE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_PREPARE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GOALS
    value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/console-plugin-rhel9@sha256:e698129f874cfc36571997d1bc4c8dbc6ad6e4ef0aca897006e11572f56ea55d
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-bundle-rhel9@sha256:0dcfd72cd012c1ec95f1f8dc826dd8afd7a54644989ee84b4de8e2f54b08094d
