versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:f0cab125777c084d4a808327aacdfa6b79d2a1a47517a2ae87d4aceca9d51aa1
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:af39846cfc8e20b7285bedb3cf92e7addc9150abc4b8d048fe3ff8654e94bf1f
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:2da30932ab26bc2dca3db949d0648278a967774de7dd68fa147d1486c23bcfcb
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:9e93d352bf54e469dc6cf70b8974906133859c771607ae6bdef8b93ddfa95ba3
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:a3d7269e1be4216c4a2bfd70fd4a18f8e5e7936ce8ba7b992a81bebdb46545aa
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:75134132f626582040168fcfeb85241b4362466a93a80a97b9fa2097b12b7beb
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:6a26c835f21e4165f89c126485e85d7c12ba2c430722cc3550ca7618d1116540
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:a3d7269e1be4216c4a2bfd70fd4a18f8e5e7936ce8ba7b992a81bebdb46545aa
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:cdf91e123cb9209d308d22927e454834b819b5095214b488bc8dd4c423cc34fb
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:a8c4dcbf338ce195f6487bd534fe8a32ed14ed50826381af9f7b78e39e399d85
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:f76ce397cb2005b7700d747c706129dd07eb64a953fb082f57052745d96dc2b9
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:5be559c545f6dd0eda6e51a509e875fcf8779f445abb25cd043e5120991cc731
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:4a7529a7f91dbc85b77d0a1b9bdf1cd2d0b4ace9b137d7f7cc199c21dba4bc88
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:755636464f76eea41ccd79c24a679a05391bc4e58662112e4d6c2d904ea9a5ca
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:cab1c265f9a83f16101dd8b866d5bafac58efed43fed3c631587d63e2e90668c
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:92aec9145c3b6489dba92dbc1452d7357f084e8292e2ceea76c31db87022ec92
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:f0152a56754acc93f64448878cae4f0240b32c857f9b2a37f02a20bf51c2f07f
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:c451b7efacf87f9a015321870cde5e674743226fa2e3bc16f72cacf108b937ee
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:338e3ec5f76f1344deb63ff3e6499243a8a23bd7034366370f1e713b6c2017aa
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:b8d7dc1aa44ba096bad8254f8e30a910a2a9898b09b5ac1be51a229350cc0b5b
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ec3a3b5ec38852a018a9de81305815630ac83d7b7052324cb325039dd5143821
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ec3a3b5ec38852a018a9de81305815630ac83d7b7052324cb325039dd5143821
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:ec3a3b5ec38852a018a9de81305815630ac83d7b7052324cb325039dd5143821
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:9c387415e9268a0c4887dfb356d07a4156395d62331019bdc19469e33048d346
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:0a1d10debf281342b52fb500d59eb6659df1ecfcf34139636a4c85c70650a7cd
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:0738c6f2b35372cba11c3d39d6126757baa7818cee5b0aa5edc5c16a7c745faf
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:e1249b9e36bbcf3e7125ddac388f35db37226e4b7dbc67f9152278c95bf60ae0
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:21db738e30cb30dc8a071e9fd8f39b8f946656bbbf6d27ccad40ba60cec31df4
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:c81860fa804a9df62feeaabb40eeacaf367910ce78dc64d5605f33f7a90fb158
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:e9e08cf295afeb5a1f02eec4fac848d25a00f6e86d74c28f2977ff0456852249
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:e9e08cf295afeb5a1f02eec4fac848d25a00f6e86d74c28f2977ff0456852249
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:b6d8df460c66e35701893823e070ea8c856d34fd7ff2d3f2009a5585a2c44087
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:d3f90463d9dec7369c74444d3e7074554fad3443353574ab9bce9dc5c3df5166
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:c71c1dca4fa3d71abdbd0ce2a02e37cedf4f885b274c3834f183379106fc96c5
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:c71c1dca4fa3d71abdbd0ce2a02e37cedf4f885b274c3834f183379106fc96c5
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e011bbb2dbfb36e152c46aced3b23c1f622d68f34fa7a7bc7fc007c12167ed0e
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:8a7a419d41837fec32726f0d94f893609d60a3915bcfb628b3e9211193d98e1e
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:f001b5c39875c0822405b5576a7ba5b1318b440c4c8911dbfc001fcfb19aad72
  # opc
  #- name: IMAGE_ADDONS_OPC
  #  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:6575c7b3dbd9c4c8756090958d817c301e8e5c86dfcac01ccc0e34463bb69f3a
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:8b3074066f9209a9187cc76a171d033d2ff910278b519ef973730b637c10f387
