versions:
  current: 1.18.1
  previous: 1.18.0
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-controller-rhel9@sha256:e0fbc888eccc6106234eee6dafab0f03c915404f4a881164cecdb6478fe11ebe
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-webhook-rhel9@sha256:83861c65d9c4250fee31ecb37808544cf65a8c220f2a8d0a27ef1585ef79b1ff
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-resolvers-rhel9@sha256:7d87bc02a012c6d4f84ffdbf7f196d250e7f36c0e34863965deb6e139e7a2f30
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-events-rhel9@sha256:64e31438e0d59603191797fe18a445105e9e474fa7019d4126a8028b28197aea
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:8e66891e7607947cc9cad8fa09fd966e362c4d15207129c4b94eed7c4081c750
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-workingdirinit-rhel9@sha256:6bcea395d5c86b2704c1318a88eab61617f9e9a13aa62b020f8b68bd90b1d4c8
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-nop-rhel9@sha256:7a7a46385b9e3d93af655eb72313e5ee97b2e4719b694bf848a17b163848c611
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:8e66891e7607947cc9cad8fa09fd966e362c4d15207129c4b94eed7c4081c750
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-sidecarlogresults-rhel9@sha256:eabe99acb49a4b57534145ac96a726a64aff1b8343813f6c63260aafb8f00327
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-controller-rhel9@sha256:ca464cd6117acca56ba37af1d71ecc29af07c2d9f5f6d3c9c6168614d613d5ca
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-webhook-rhel9@sha256:a9bfb172695ecf2ee0863414ad31e56fa90f2f63a7824a46f606d28c3ca0c273
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-core-interceptors-rhel9@sha256:592e1a98d2c67a97d8aa79a6fd822def0a46246e56ad38313b509864be3ec47c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-eventlistenersink-rhel9@sha256:18ce88e2ca9c3ef380feb16e081a138b40adbed8b3c9f1633479bf0f45a29872
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/chains-controller-rhel9@sha256:c0c85f6c58a14dfaf7f85b73639a9f00373e862779b3b7d98cc0b270a7a926a4
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-db-migration-rhel9@sha256:4077ee1c1d0fb4529025352e55fa11d7804f412c7e66a909eaaa6149afa7e196
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-api-rhel9@sha256:8b9a52b748a65e337521834bceca1d68f28150ec99201b6e5bb503564f645963
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-ui-rhel9@sha256:b0240011308e6a77ae2b0bfc79c58bbe1066200295c1d7cc857d2a76f26b68e0
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-watcher-rhel9@sha256:c71cb29b50734ebf7338aff500a432f960e54a371221f52241215e8b3ad55884
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-api-rhel9@sha256:a2d80f9b4048b758c3d767af46133b119723ed995202d3324c417995453c49a4
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-retention-policy-agent-rhel9@sha256:e371b11a4fbae4fae2a356abc44a81c87e9495348de1412fd183191215218eef
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:9613b4fbf6b5b86d13880c448fe62abdc11b38fb05cd464eaf4a88a1ce490e5b
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:9613b4fbf6b5b86d13880c448fe62abdc11b38fb05cd464eaf4a88a1ce490e5b
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:9613b4fbf6b5b86d13880c448fe62abdc11b38fb05cd464eaf4a88a1ce490e5b
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-webhook-rhel9@sha256:92ce4259bb9f915fe6ccae9f11caa2c6481b901f8d18ecf3aef55ab9392dfe6e
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-controller-rhel9@sha256:7d1ce653618324fd7c24f40d8d23f66ddf11d11169a27959578f7d82e580823b
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-controller-rhel9@sha256:d9d06a4747135d27653e91567296e2eed4fa821ab7247d54bff5681baba19947
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-webhook-rhel9@sha256:8756eec31bc8e89d423a4ec000db937f4807fe71192ecc65d85fe87fb0052954
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-watcher-rhel9@sha256:8e221b92f230c9ee72b23c5463bffc731c64434fa81fbae6bdce3af7917cbb53
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-cli-rhel9@sha256:b7dfaad856a1d4a856946d12dad3783dd5c04ecedbb76e3dfc8ee13405351b89
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:58ce00263c08454d253024641a1f3da643fcd46bb1a90a2099c61beaab862bcf
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:58ce00263c08454d253024641a1f3da643fcd46bb1a90a2099c61beaab862bcf
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-proxy-rhel9@sha256:36723896d37c8e5ea014c15d4b689cec6330ba829d4eda440ff2ae0234f3a17e
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-webhook-rhel9@sha256:3f52968d6aeb34cd573a6bcd71783a05687eae2e6cb26fee58b72e63a3be39c4
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:1ada9cfd6bc3efd70172b87674248dd0ca52f9b2a6797e84cedbd07920e2a6c0
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:1ada9cfd6bc3efd70172b87674248dd0ca52f9b2a6797e84cedbd07920e2a6c0
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/console-plugin-rhel9@sha256:450864492e82a5b04b3015407599686ed9a8a9ccf9c60f12fd3a960ff9fd9876
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-bundle-rhel9@sha256:f44fc6b084ab2fffc1f2b8bd5061f48e140bff006fe43b35abb8a2c8d4b66b48
