versions:
  current: 5.0.5-479
  previous: 5.0.5-478
  previous_range: 1.16.0
  channel: pipelines-5.0
  openshift:
    latest: 4.17 # lastest GA'ed openshift
    min: 4.16    # Minimum version OSP supports
images:
# tektoncd-pipeline
- name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/controller@sha256:ef21fab35f2b75facc850d60ade4b713f92c39b3cf20f418e9d08aac84e86244
- name: IMAGE_PIPELINES_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/webhook@sha256:a16fb747e2a0192139a1206035045c467ff733514977ef63571630abffd8464c
- name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/resolvers@sha256:3fed9bef9b576b0988d88b32fa7bf24ba5d8fc79dbda4ca27a287c41c4a4f1ef
- name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/events@sha256:88a3f15c8005206fb5242b1b663fda59846e67cccd2fc2cd731242feee1d546d
- name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:30984ae3cd39b2fa4155f98f7e37550bd9dfd862dcb13fac3dacf6a25b1eaea4
- name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/workingdirinit@sha256:8c7fdd8cd712115a559f4d267383ee79638e8f89c5249e704d43df271e6f0e70
- name: IMAGE_PIPELINES_ARG__NOP_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/nop@sha256:c74e314c2fcd0de66b6862ac1b2efaacb50f67365d66fd050f87ed5ec57ea2d6
- name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:30984ae3cd39b2fa4155f98f7e37550bd9dfd862dcb13fac3dacf6a25b1eaea4
# tektoncd-triggers
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/controller@sha256:c56891b292b72f267aafd0506b19bd1cf47fe48b3cdf543cf2d62374d82bf4c5
- name: IMAGE_TRIGGERS_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/webhook@sha256:091bd90280b5ececb253f0a0c4601be93e6adea15e9a109d9db88b306bf1b31e
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/core-interceptors@sha256:c45ed28d7782cd2269735ba66c1a21ab443fff8cef14dffd0b7b340ec200264a
- name: IMAGE_TRIGGERS_ARG__EL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/eventlistenersink@sha256:f6a6fef74bad2239e8dca940e8c9e265dedc7806085459ec9d1ae7a428c1a07b
# tektoncd-chains
- name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-main/controller@sha256:9c98308aa88fe6544f2d703a6fcc64b300fe6ced144ac15c61f13c35796a8f35
# tektoncd-hub
- name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/db-migration@sha256:317641aa2b46f200f91462d84c115eeb9a20cb8307d879e1d6813664c1a7c606
- name: IMAGE_HUB_TEKTON_HUB_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-api@sha256:a8279abd3494d759efa2dcd2cf1dc9abe850b74a8325deb0017ae39d297eccf2
- name: IMAGE_HUB_TEKTON_HUB_UI
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-ui@sha256:329c09c5895299834e19b09a1f18a22fae57ec8a4c4937e311275370282a7ac5
# tektoncd-results
- name: IMAGE_RESULTS_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/watcher@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/api@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/retention-policy-agent@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_POSTGRES
  value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# tektoncd-cli
- name: IMAGE_JOB_PRUNER_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:95c266eb1e1b9b7407ba0b8c7fd734f81176e6ecef5d8043ffef92ed83874418
- name: IMAGE_ADDONS_PARAM_TKN_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:95c266eb1e1b9b7407ba0b8c7fd734f81176e6ecef5d8043ffef92ed83874418
- name: IMAGE_ADDONS_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:95c266eb1e1b9b7407ba0b8c7fd734f81176e6ecef5d8043ffef92ed83874418
- name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
  # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
# manual-approval-gate
- name: IMAGE_MAG_MANUAL_APPROVAL
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# pipelines-as-code
- name: IMAGE_PAC_PAC_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/watcher@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# operator
- name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:26c0bb8d7d11804de3cd42c32b247c9a151b0bc294793f235e478383534bd410
- name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:26c0bb8d7d11804de3cd42c32b247c9a151b0bc294793f235e478383534bd410
- name: IMAGE_PIPELINES_PROXY
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:e6f6c460ded3823a4b41e155ce06d6757c7e4ff3393788865f6ff0590d39f566
- name: TEKTON_OPERATOR_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:05e2ff85bebedf85071c80457508a78be05a9d51051723d0cd0fd8202b543001
# Addons
- name: IMAGE_PIPELINES_ARG__GIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_PARAM_GITINITIMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_RUN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_REPORT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_CLONE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_KN
  value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
- name: IMAGE_ADDONS_SKOPEO_RESULTS
  value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
- name: IMAGE_ADDONS_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_GENERATE
  value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
- name: IMAGE_ADDONS_LOAD_SCRIPTS
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GENERATE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_PREPARE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GOALS
  value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
