versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:4b714b855692195a16d655e785c94565b937ab94a63ae6a0137a404847979ec2
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:fdf6f0eedb7a7412912b3e0af9afde4eb53120811f7975c1f313849456d446ee
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:d31dbaa528825e9b6eb8879700352a24959e2f72fb2c220035555f1bad340b83
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:3c4af2c7ffa760cb5f9b208006d6165ae8e35ce0ed182f1633e76d45c4e2a5c6
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:017a2cd199c832283ce9a58841ed0b37c63c93eb5159b31d4b30f4ecc921cbfc
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:54b7ea9e160153cf4f0ae28bb539844d28c4a73e72151ded257a833bc5b443ac
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:0365c3c7d9c1c267e5938142421cb8690be4d67bfd89fff41ccc06267094b997
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:017a2cd199c832283ce9a58841ed0b37c63c93eb5159b31d4b30f4ecc921cbfc
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:560da746e98393767131bb5cfd3f5f59890b5f84f3ad89fe9fe308d9d8851b12
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:2beb9440193c23b72b6ab244eaae6037d4b5ad52cda95e1eab4a84df8fd83f9c
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:fee46dd9a1945763cbd4f8a6d34c2b1794d60fce2736f2b16f3be83410bbb2d9
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:de1abbee622315eb7a233487cd9a9b92c8d15ced1edf914c0f403d769db76b7b
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:60f07652693ab3424f60c5326ba8099dc002c036ebc12812a263a3b3b7ae9f0a
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:cd5d383a159b6340a35249ee673445da22bc04f5cd3d7c7e7417fbf46ef5baf2
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:ca856be34e0ab18e24e27278dcd82fd123a0e603f204bbd2054edab205140539
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:ec5fb350a4544e0b8570f2ba1a8fb85d816658b3fce902cdddd24a1486697f9e
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:5a6bc4b66cfd1be44d01c11fb2903d77ecd69001b1083972cf3643484f0f76ed
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:dffdde967fe1dbc09255d9a5135fab0536509784ecb53ec6f0473dfe6dcf36f6
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:c418abd9364697682b9ebb47be12013f94ac16a5fc13ffffab8ddd9ea693c860
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:d46ed4f3f6aaf32441715ad0584c42396f549a958af1a8228a39aad670ad9376
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:7634eb1d8eaa2d86790429d4b4d0b539dc01c0bfb982fb9fc54229748d612f10
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:7634eb1d8eaa2d86790429d4b4d0b539dc01c0bfb982fb9fc54229748d612f10
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:7634eb1d8eaa2d86790429d4b4d0b539dc01c0bfb982fb9fc54229748d612f10
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/openshift-pipeline/pipelines-serve-tkn-cli-rhel9@sha256:800d8d053e1e6f8335ebc70e3280a56717bc1186461125c00b2a5c5e6f2c52a2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:8e877b845f8e8895ce0841f0a5a4a3d320f9aed11354e7a1995cb797a49ea6b0
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:b8c6a292084db236cce68e6b6824ca3547dfcb1239e8a9849d951bc6c260d6c7
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:356b9d68ac47a82f3476227cfe34c1e69973ca8b9d59921c2505a1eba52a7aa2
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:3e98a5699cb5caa7876c7e94f65385a97089e0ec40d60a076b974196d92e88a5
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:41a1f0b7d9eb70835eed950ddacbe6527e0a4071928c8f57157ea7de9bfffa5e
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:e7e74ebf4f4ea4285976b27bbefab1be57420ac4b4d4c5b18c7652cf48464c62
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:46964f101beb0b2374eae154d9b29679e60ecc9e5ddbf27e5670e6b4fab19df4
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:46964f101beb0b2374eae154d9b29679e60ecc9e5ddbf27e5670e6b4fab19df4
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:10217f0993322c1b1f3f1d61a7368e52874799e29698d83753e5ace5c637d1d7
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:8e2d79a7f15b08d929656d2a5d60bbc7211f86e71e30310eba17e537b41c79ff
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:4bec53cb6db4e6b5eb1668af71e32ffc22d83837435e8d80011c212f59f6a543
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:56bcf79db07c9400ee69471e84526d0e45ef85b7e7c5fbeb6dc4689eaeafad85
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:11203b74adab95d2dd06115f0fbb9a722563eb43c770da092663207c79d28f54
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:7b141e4df33820454a104b3f229e64a55505d6387ec04d57cdd3eb620c3dbfd6
