versions:
  current: 5.0.5-594
  previous: 5.0.5-593
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:a10f2e5d8c6a463a6049e6e8f05f2b525d3871e23b3b4df90b5921fba144092e
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:136dcd95c4fd5e3d6fb2fcf77e2448cc5de7303b6fafdfa874657d451eb3fa14
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:7ab145c0c8a1b129bcad56b08dd6c9d481cdfb6f2953f2105a7d8150365fefdb
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:bd1718d847cb37a6880e0956df066a01067fad0573a6b26f317654b0b647a898
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:d21987d40beeaa12be2ec0be47d4a1e7766b839dda825381e5be777e90971b8e
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:0a80d0abc8f41386f3914121423ca9a52c1f741b1b5284334f7dc1a0de5d628a
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:4f9027fd42e2f1356fe1f9a59e68d910054476bbfe3a18d6ea7b5ca9d9d83357
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:d21987d40beeaa12be2ec0be47d4a1e7766b839dda825381e5be777e90971b8e
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:2d6bd30c310f1ff73e03a13cfa73250b7c67b5855e00737174dbcde108a2a4f1
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:4b337ab5b7b9cdfe17538d84c62f29067e9590618181186f0406ec6253962bf8
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:8e64fa62f96fe3064fcf768cc14100136bcfeaa22b2ac3d77bd8277ff63f4ff0
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:14d76da9a1a4f6fbf271d78fd55d25f13af7ac3afad7b1fb92acfa117258098d
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:ed6885311d7dbf3846183fcffe9c076ab9ab7d5e1c174e524e343da3c7613723
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:20038e2bb5ef012c6cc9c3ac1c8ec823189734f9c81e7afc5c9ce124d26eef67
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:f338d5cc660453ac914be9c5567e454aeb93aec877231560cda700326ff998ce
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:8324ae6670be16ec7eece11e686b9aee0d9a10ddfb3feacacf526b281142a8d0
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:2aa716ea7489a9a0f3e75f4b0dcfb5f6914f5065ab99847c7ee4095652281032
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:9844545278e3e4acdf79b2ff0200a260b0b403a92de305adb47fb115a18e7f64
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:11a65cf44d02281931bc3c626a4a95a47048ad780589bd8921a1fa43c416f8f8
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:22b0190ce475791f595f40ace3c1931c9e6da06b1930038bd117ea6361784d29
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:0b1e544977a53b610d3a65fd128961742260ab17a94d511f668bcc9cfe79e7c0
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:0b1e544977a53b610d3a65fd128961742260ab17a94d511f668bcc9cfe79e7c0
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:0b1e544977a53b610d3a65fd128961742260ab17a94d511f668bcc9cfe79e7c0
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:7cf31108549190c3b3b7d1c83d906be5f51614f9bf65d5fe7b3a3f93244d7843
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:a398b4a7fd7b5d8b7eaf171bfd2f061d90d7c8287cb3ab171ccbfeeed5efa9d6
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:3ff0097701fc6e1de5edda5f7c0066249273bcd705aec77d7c5dfa521648b89f
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:82481553caebddde61c6c1adb61306f17fd104cd126a02f095704b563c55c5d1
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:66f8c53b9c4d6afc2af8d4ea84e530b5339a9f17bb9266bec4e48ed576fc0598
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:d8c565bfea2edc4f6b3af935b38635d679d8c9ca5127823a9e14081f4ede150c
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:977fd2d48245db7285e4e65e8944d1c127975bb4446c62934bd34e3f3d62618d
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:adc010c520645982b711031d300c3905291a3c3ab5344fd54397832ace672ded
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:fa429f093d32f1899b19b6480e5f0aec9b32836941ad41d6db1335f07066b902
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:fa429f093d32f1899b19b6480e5f0aec9b32836941ad41d6db1335f07066b902
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:d4a23b1e610fc3c63f13a7eab3de5d48d9d364e01c059cab446cab45f1300bd3
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:d4a23b1e610fc3c63f13a7eab3de5d48d9d364e01c059cab446cab45f1300bd3
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:d4a23b1e610fc3c63f13a7eab3de5d48d9d364e01c059cab446cab45f1300bd3
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:d4a23b1e610fc3c63f13a7eab3de5d48d9d364e01c059cab446cab45f1300bd3
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:d4a23b1e610fc3c63f13a7eab3de5d48d9d364e01c059cab446cab45f1300bd3
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:d4a23b1e610fc3c63f13a7eab3de5d48d9d364e01c059cab446cab45f1300bd3
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:1d5542602fbc466cf9641e144a7f14aac94146c9e283137b58eaddd32188c823
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:9ac7d833533a29215be25707c491c2fbcb5ec9023accfd9366f041a3963283d5
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:d4275b1ac163018fbbcc32eeef9ba7951de518df0f61775b7a3ecf78e477108a
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:491f28e91b431dadaaf5fabc877814b5d8649cb2b70b74467ff0744a8bb7f84e
