versions:
  current: 1.18.0
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/controller@sha256:3eb15926c61ad92aa49f149d53682f16c79d743b98082bc12212fbc23840f0bd
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/webhook@sha256:faedb3ae10e9bc591ef67b47cad737cf83f5b1ee61b7f7289875d6ccc9cc1876
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/resolvers@sha256:55b8bffd1f739bb1f7882d2dcab33b936bea8c779b3403e3a1bd37ea2d690e2d
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/events@sha256:72eab6f307eb83a4c5efde65be1b8589614690b923cad21cda00f269bdfaf61a
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/entrypoint@sha256:b16a3a221740044dbb888fe5384b1cdaf878bdd691a99ec2b316d33730f10c5f
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/workingdirinit@sha256:77440614a942c9494ecca2c70d73d36d33297eae7dab2cae01f823a860f0573f
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/nop@sha256:496967f2e62ade2688614e26170e861ca6cd5939ee33cb78b8eebc3b674ff354
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/entrypoint@sha256:b16a3a221740044dbb888fe5384b1cdaf878bdd691a99ec2b316d33730f10c5f
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/sidecarlogresults@sha256:f32c40d3e7b5de94927637eaf7e3157d65e901af03339d32532cf4566aacdc35
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/controller@sha256:effa049f24560ac2b1b56281148c034d4b437a1896254855bb0afd6a73399e2f
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/webhook@sha256:932bf5baa96b8a87bf567536da20f5367420872340097fb4d676c7b217847fd0
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/core-interceptors@sha256:c25b783105408a4d2b07fc9f3af45eaaf57283b5388fd85bd1a4723c53491bc1
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/eventlistenersink@sha256:9f16970689ce90f24b53b536abf0dc93af588f2e43011087fb9c471de3a5b29f
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-1-18/controller@sha256:b7071b1a1762f3d2f3c9160c276292c11db681164c251c20fe8e1f01a0db7da2
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-1-18/db-migration@sha256:4558e4cf1a21e9594322415a3579b7d3e24ae3af5423beaaac143d3f00b9886b
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-1-18/hub-api@sha256:f2bea5703fa6d2a2243532fbc7b8bd9f1927f8c341ed1387b5d2d8c438b7cf2f
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-1-18/hub-ui@sha256:c6e243902d39d4ff9cb2f99813dc53b16bc5a209dde760e7c037268ee8c98b24
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-1-18/watcher@sha256:032b45dfe3c17f20c4879398ad5183710484ac2c79fb009873c90e92a491ca99
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-1-18/api@sha256:802ec0fe73c96dfce4d0bfe25840f92007f24298e91d8318b4153703b290ca1d
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-1-18/retention-policy-agent@sha256:5b57c5bf7437ec7b0810613e80536272bb27ac74d931bc3ad371c37787450adb
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/tkn@sha256:2ffe3a4418c36db5b9f88e3fa774f63afc4931b5bedb4534079f4d125dd55760
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/tkn@sha256:2ffe3a4418c36db5b9f88e3fa774f63afc4931b5bedb4534079f4d125dd55760
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/tkn@sha256:2ffe3a4418c36db5b9f88e3fa774f63afc4931b5bedb4534079f4d125dd55760
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-1-18/webhook@sha256:64cd665d4074fc14743a80722989bc517cc957d12fe2e82ed6819cde6fd3420f
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-1-18/controller@sha256:395d685d6066ea742bf0647013df6986d7df90a4c521669c69d39a210c1807f6
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/controller@sha256:b19ba67130a02665964c65dc60dd20f3ffa159079c393e8198ab33434b23d671
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/webhook@sha256:4b8701f4f43b75b5e7752d3b61fc0106fa472b1b710d049bc9b1348c961d3fbf
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/watcher@sha256:09ebe8b449ab1eeca3aab0b5425b90e45eb026f439a8aa07e34d7d3e116251fd
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/cli@sha256:501a80346d830b58c0e1f2a8597925d63aec9d78790c40d5d08cece9411651aa
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/operator@sha256:9f21851084121ccfabc07f9349bfd4236a4f589e255a9690b60d6b3b5f9a6c6b
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/operator@sha256:9f21851084121ccfabc07f9349bfd4236a4f589e255a9690b60d6b3b5f9a6c6b
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/proxy@sha256:fdc8fb39ca8a7c3a18ab75f3824845ce71d099f5e34dbd47b385b55efc9dfdb5
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/webhook@sha256:78c0afae2841835584ad2b26368d85666915d4862e13a1e411237cad3575fd42
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tekton-caches-1-18/cache@sha256:500f07c6025939037d0ece18bdb714872261b7f373f7fdbbabb4f997dabf1f88
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tekton-caches-1-18/cache@sha256:500f07c6025939037d0ece18bdb714872261b7f373f7fdbbabb4f997dabf1f88
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:eabf3026646da4c467d907e90a36bbdb51bb99cddcd14763ea74d9d7b983790e
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:eabf3026646da4c467d907e90a36bbdb51bb99cddcd14763ea74d9d7b983790e
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:eabf3026646da4c467d907e90a36bbdb51bb99cddcd14763ea74d9d7b983790e
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:eabf3026646da4c467d907e90a36bbdb51bb99cddcd14763ea74d9d7b983790e
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:eabf3026646da4c467d907e90a36bbdb51bb99cddcd14763ea74d9d7b983790e
  - name: IMAGE_ADDONS_KN
    value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
  - name: IMAGE_ADDONS_SKOPEO_RESULTS
    value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
  - name: IMAGE_ADDONS_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
  - name: IMAGE_ADDONS_LOAD_SCRIPTS
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GENERATE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_PREPARE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GOALS
    value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/console-plugin-1-18/console-plugin@sha256:857bdf8fa39d93234b7ecf310fb894c095260d58725b653314d52322e9c4fec8
