versions:
  current: 1.19.0
  previous: 1.18.1
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:4b714b855692195a16d655e785c94565b937ab94a63ae6a0137a404847979ec2
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:fdf6f0eedb7a7412912b3e0af9afde4eb53120811f7975c1f313849456d446ee
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:fc35b92963d700cd69abe40a8a00614e97ece46277d779ca394e1b468e6eb72f
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:3c4af2c7ffa760cb5f9b208006d6165ae8e35ce0ed182f1633e76d45c4e2a5c6
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:017a2cd199c832283ce9a58841ed0b37c63c93eb5159b31d4b30f4ecc921cbfc
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:54b7ea9e160153cf4f0ae28bb539844d28c4a73e72151ded257a833bc5b443ac
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:0365c3c7d9c1c267e5938142421cb8690be4d67bfd89fff41ccc06267094b997
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:017a2cd199c832283ce9a58841ed0b37c63c93eb5159b31d4b30f4ecc921cbfc
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:560da746e98393767131bb5cfd3f5f59890b5f84f3ad89fe9fe308d9d8851b12
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:6c1e11b10f62897af4db640e821bc948b274b950e25b4b8571b7178998d174e2
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:6ad43ada4ab734381ed6eb3a20d818ec7d376dae5b45b49e6e550ad170afc603
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:35552d8d69e8515753a737c3cdcc09a030fc93917257257f51719ed887483c5b
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:fd9df98dbaa22044fd7d0f0bed475e12e859a40ffac210adae4217be0454742b
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:20038e2bb5ef012c6cc9c3ac1c8ec823189734f9c81e7afc5c9ce124d26eef67
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:07a740e6b8d5c71c0f1c0cca366ac62aaa42b0ae2647fec38b82514859dcdfa7
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:5b3fe070ffa0618527c8910c46aac6698fe485e71c93e37e88a6f8dd193d4f57
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:e487033dd5923001566b2b35f86f074e9f57732cf050cd0c8c14969047ffaac8
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:906af1517db0a4a6e3b2540f69de9f89c94c6b390b96cd4084f84ab8f87193ae
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:185bf0baeb1c4e3ee9f846b0ff1d6c2439c637f0d8f07b6a86e71f811c3161d0
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:ce75b106a5ee86bdf77a27ee35ddeaf56560eeaa2f845fd997fbe1ba48bc35f7
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:5bee85c60e8fe504eb4fce65dbb44cc7d97cb0d76932d3789206e75735409167
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:5bee85c60e8fe504eb4fce65dbb44cc7d97cb0d76932d3789206e75735409167
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:5bee85c60e8fe504eb4fce65dbb44cc7d97cb0d76932d3789206e75735409167
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:906dfd12dba6aebd255ed89712535e178ee2b134cfc13b60aa51c760a05de0ff
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:b3bf2bcaec2d994f700993aae199cacbc70a6881371b2afc566f194545e544b4
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:397393c99e14f7837433426561137e29deda192b25303b37db1d537d6f83a2f8
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:b9d7c14cb936991e57b88c8add96e4315e87b906a77b80188b9871db0661e135
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:af2329eea0532f39da4a367b86b7708547965031b578f4c14b6d970f33f9981d
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:56afeb4cdf6cb7188a5af77d7eaace6d499d7c977e96e644890f91eb8262c65d
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:9f8a53f830a8d6f14fec13d1c74143dee05aa476f07e66d9d871dbb6a9a8b781
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:9f8a53f830a8d6f14fec13d1c74143dee05aa476f07e66d9d871dbb6a9a8b781
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:0ed189773c2590e84db2490fab0db56c8190bbacff6e8a4623ffe20e1e9d9d27
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:9bd5cb732f33a37922970b1ae69be346d96eac4b9d362e52b587a4a8bd56c7c4
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:740b9f27f99938f98f5a0ab839029ddd4fb3a49e21ada26e2ebff7396afc9467
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:f89ff9d7abff86b031477ca7b56a91b1246990245724b0b3b54d1a1ab20d3e11
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:4bec53cb6db4e6b5eb1668af71e32ffc22d83837435e8d80011c212f59f6a543
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:654897c27f8eb007bb978bf40016f4e7352a26ee0ed52cf7538d0c474e2d4b68
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:7497dd80a619eff70d1b52c038290e43cebaf1bd69da5773455942fd24a56817
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:814dded254545447356de82d3644b124329fa61c63be7b2cbf8722ceffa47e1e
