---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    image.redhat.com/generate: "true"
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    image.redhat.com/generate: '{"visibility": "public"}'
  name: operator-main-webhook
spec:
  componentName: webhook
  application: operator-main
  source:
    git:
      url: https://github.com/openshift-pipelines/operator
      dockerfileUrl: openshift/dockerfiles/webhook.Dockerfile
      revision: main
