apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: operator-main-e2e-tektoncd-pipelines
spec:
  application: operator-main
  contexts:
    - description: E2e testing for operator-main-index-4-15
      name: component_operator-main-index-4-15
    - description: E2e testing for operator-main-index-4-16
      name: component_operator-main-index-4-16
    - description: E2e testing for operator-main-index-4-17
      name: component_operator-main-index-4-17
  resolverRef:
    params:
      - name: url
        value: https://github.com/openshift-pipelines/operator
      - name: revision
        value: main
      - name: pathInRepo
        value: .konflux/tekton/bundle-e2e-pipeline.yaml
    resolver: git
