apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
    operator.tekton.dev/release: v0.73.2
    version: 1.16.4
  name: tekton-operator-webhook
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app: tekton-operator
    name: tekton-operator-webhook
status:
  loadBalancer: {}
