---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: operator-next-bundle
spec:
  componentName: bundle
  application: operator-next
  build-nudges-ref:
    - operator-next-index
  source:
    git:
      url: https://github.com/openshift-pipelines/operator.git
      dockerfileUrl: .konflux/olm-catalog/bundle/Dockerfile
      revision: next
