apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: operator-next-e2e-tektoncd-pipelines
spec:
  application: operator-next
  contexts:
    - description: Application testing
      name: component_operator-next-bundle
  resolverRef:
    params:
      - name: url
        value: https://github.com/openshift-pipelines/operator
      - name: revision
        value: main
      - name: pathInRepo
        value: .konflux/tekton/bundle-e2e-pipeline.yaml
    resolver: git
