apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: operator-next-e2e-tektoncd-pipelines
spec:
  application: operator-next
  contexts:
    - description: Application testing
      name: component_operator-next-bundle
  resolverRef:
    params:
      - name: url
        value: https://github.com/pramodbindal/demo
      - name: revision
        value: main
      - name: pathInRepo
        value: e2e/pipeline/tektoncd-pipeline-main-e2e.yaml
    resolver: git