---
schema: olm.channel
name: latest
package: openshift-pipelines-operator-rh
entries:
  - name: "openshift-pipelines-operator-rh.v5.0.5"
---
defaultChannel: latest
name: openshift-pipelines-operator-rh
schema: olm.package
