on:
  push:
    tags:
      - '**'
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    name: manual approval gate release
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: write
      repository-projects: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup KO
        uses: imjasonh/setup-ko@v0.7

      - name: Manual Approval Gate Release Started...
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "***********************************"
          echo "Latest tag is: ${latest_tag}"
          echo "***********************************"
          
          chmod +x ./release.sh
          ./release.sh "${latest_tag}"
