apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-pipelines/operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/operator-main-bundle-push.yaml".pathChanged() ||
      ".tekton/operator-main-bundle-pull-request.yaml".pathChanged() ||
      "image-mapping.yaml".pathChanged() ||
      "openshift/olm-catalog/bundle/Dockerfile".pathChanged() ||
      "openshift/olm-catalog/bundle/metadata/***".pathChanged() ||
      "openshift/olm-catalog/bundle/manifests/***".pathChanged() ||
      ".tekton/docker-build.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator-main
    appstudio.openshift.io/component: operator-main-bundle
    pipelines.appstudio.openshift.io/type: build
  name: operator-main-bundle-on-push
  namespace: tekton-ecosystem-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/bundle:{{revision}}
  - name: dockerfile
    value: openshift/olm-catalog/bundle/Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      {"type": "rpm", "path": "openshift/rpms"}
  pipelineRef:
    name: docker-build
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
