apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-pipelines/operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "next" &&
      (".tekton/operator-next-index-push.yaml".pathChanged() ||
      ".tekton/operator-next-index-pull-request.yaml".pathChanged() ||
      ".konflux/olm-catalog/index/Dockerfile".pathChanged() ||
      ".konflux/olm-catalog/index/kodata/***".pathChanged() ||
      ".konflux/olm-catalog/index/metadata/***".pathChanged() ||
      ".konflux/olm-catalog/index/manifests/***".pathChanged() ||
      ".tekton/fbc-build.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator-next
    appstudio.openshift.io/component: operator-next-index
    pipelines.appstudio.openshift.io/type: build
  name: operator-next-index-on-push
  namespace: tekton-ecosystem-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-next/index:{{revision}}
  - name: dockerfile
    value: .konflux/olm-catalog/index/Dockerfile
  pipelineRef:
    name: fbc-build
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
