---
schema: olm.channel
name: latest
package: openshift-pipelines-operator-rh
entries:
  - name: "openshift-pipelines-operator-rh.v1.14.0"
  - name: "openshift-pipelines-operator-rh.v1.15.0"
    replaces: "openshift-pipelines-operator-rh.v1.14.0"
    skipRange: ">=1.14.0 <1.15.0"
  - name: "openshift-pipelines-operator-rh.v1.16.0"
    replaces: "openshift-pipelines-operator-rh.v1.15.0"
    skipRange: ">=1.15.0 <1.16.0"
---
schema: olm.channel
name: pipelines-1.16
package: openshift-pipelines-operator-rh
entries:
  - name: "openshift-pipelines-operator-rh.v1.14.0"
  - name: "openshift-pipelines-operator-rh.v1.15.0"
    replaces: "openshift-pipelines-operator-rh.v1.14.0"
    skipRange: ">=1.14.0 <1.15.0"
  - name: "openshift-pipelines-operator-rh.v1.16.0"
    replaces: "openshift-pipelines-operator-rh.v1.15.0"
    skipRange: ">=1.15.0 <1.16.0"
---
schema: olm.channel
name: pipelines-1.15
package: openshift-pipelines-operator-rh
entries:
  - name: "openshift-pipelines-operator-rh.v1.14.0"
  - name: "openshift-pipelines-operator-rh.v1.15.0"
    replaces: "openshift-pipelines-operator-rh.v1.14.0"
    skipRange: ">=1.14.0 <1.15.0"
---
schema: olm.channel
name: pipelines-1.14
package: openshift-pipelines-operator-rh
entries:
  - name: "openshift-pipelines-operator-rh.v1.14.0"
