name: auto-approve-konflux-nudges

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0,30 * * * *" # At every 30 minutes

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v4
    - name: auto-merge-update-references
      run: |
        gh auth status
        git config user.name openshift-pipelines-bot
        git config user.email pipelines-extcomm@redhat.com
        # Approve and merge pull-request with no reviews
        for p in $(gh pr list --search "label:konflux-nudge" --json "number" | jq ".[].number"); do
          gh pr review --approve --body "/lgtm" $p 
          gh pr merge --rebase --delete-branch --auto $p
        done
      env:
        GH_TOKEN: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}