---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  name: operator-1-18-index-4-17
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/component: operator-1-18-index-4-17
    appstudio.redhat.com/application: operator-1-18-index-4-17-application
spec:
  image:
   name: operator-1-18-index-4-17-application/index-4.17
   visibility: public
